<?php

namespace Database\Seeders;

use App\Models\QuotationCategory;
use App\Models\QuotationOption;
use Illuminate\Database\Seeder;

class QuotationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // AI Music Generation
        $musicAi = QuotationCategory::create([
            'key' => 'music_ai',
            'name' => 'AI Music Generation',
            'name_th' => 'สร้างเพลงด้วย AI',
            'icon' => '🎵',
            'description' => 'Professional AI-powered music creation services',
            'description_th' => 'บริการสร้างเพลงด้วย AI อย่างมืออาชีพ',
            'order' => 1,
            'is_active' => true,
        ]);

        $musicOptions = [
            [
                'key' => 'music_basic',
                'name' => 'AI Background Music',
                'name_th' => 'เพลงประกอบ AI (Basic)',
                'description' => 'AI-generated background music for videos and presentations',
                'description_th' => 'เพลงประกอบสำหรับวิดีโอและงานนำเสนอ',
                'price' => 50000,
                'order' => 1,
                'features' => [
                    'Up to 3-5 minutes per track',
                    'Multiple genre options',
                    'Royalty-free commercial license',
                    'High-quality audio (320kbps MP3 + WAV)',
                    '2 revisions included',
                ],
                'features_th' => [
                    'เพลงยาว 3-5 นาทีต่อเพลง',
                    'เลือกได้หลายแนวเพลง',
                    'ลิขสิทธิ์เชิงพาณิชย์แบบไม่จำกัด',
                    'ไฟล์เสียงคุณภาพสูง (320kbps MP3 + WAV)',
                    'แก้ไขได้ 2 ครั้ง',
                ],
                'steps' => [
                    'Consultation: Discuss music style, mood, and purpose',
                    'Generation: AI creates initial music tracks',
                    'Selection: Choose your preferred version',
                    'Refinement: Fine-tune and adjust as needed',
                    'Delivery: Receive final files in multiple formats',
                ],
                'steps_th' => [
                    'ปรึกษา: หารือสไตล์เพลง อารมณ์ และวัตถุประสงค์',
                    'สร้างเพลง: AI สร้างเพลงเบื้องต้น',
                    'เลือก: เลือกเวอร์ชันที่ชอบ',
                    'ปรับแต่ง: ปรับแต่งและดัดแปลงตามต้องการ',
                    'ส่งมอบ: รับไฟล์สุดท้ายในหลายรูปแบบ',
                ],
                'long_description' => 'Perfect for content creators, video producers, and businesses needing background music. Our AI analyzes your requirements and generates unique, professional-quality music tailored to your needs. Each track is crafted to match your desired mood, tempo, and style.',
                'long_description_th' => 'เหมาะสำหรับครีเอเตอร์ ผู้ผลิตวิดีโอ และธุรกิจที่ต้องการเพลงประกอบ AI ของเราวิเคราะห์ความต้องการและสร้างเพลงคุณภาพระดับมืออาชีพที่เป็นเอกลักษณ์ เหมาะกับอารมณ์ จังหวะ และสไตล์ที่คุณต้องการ',
            ],
            [
                'key' => 'music_custom',
                'name' => 'Custom AI Music Track',
                'name_th' => 'สร้างเพลง AI แบบกำหนดเอง',
                'description' => 'Fully customized AI music composition with advanced controls',
                'description_th' => 'สร้างเพลง AI แบบกำหนดเองทุกรายละเอียด',
                'price' => 80000,
                'order' => 2,
                'features' => [
                    'Custom duration (up to 10 minutes)',
                    'Advanced genre blending',
                    'Instrument selection',
                    'Tempo and key customization',
                    'Multiple output formats',
                    'Unlimited revisions',
                    'Source files included',
                ],
                'features_th' => [
                    'กำหนดความยาวเองได้ (สูงสุด 10 นาที)',
                    'ผสมแนวเพลงขั้นสูง',
                    'เลือกเครื่องดนตรีเอง',
                    'ปรับจังหวะและคีย์ได้',
                    'ส่งออกหลายรูปแบบ',
                    'แก้ไขไม่จำกัด',
                    'รวมไฟล์ต้นฉบับ',
                ],
                'steps' => [
                    'Requirements Gathering: Detailed discussion of your vision',
                    'Concept Development: Create music blueprint and mood board',
                    'AI Generation: Generate multiple variations',
                    'Iteration: Refine based on your feedback',
                    'Final Production: Polish and master the track',
                    'Delivery: Complete package with all formats',
                ],
                'steps_th' => [
                    'รับความต้องการ: หารือแนวคิดโดยละเอียด',
                    'พัฒนาแนวคิด: สร้างพิมพ์เขียวและ mood board',
                    'สร้างด้วย AI: สร้างหลายเวอร์ชัน',
                    'ปรับปรุง: ปรับแต่งตามคำติชม',
                    'ผลิตขั้นสุดท้าย: ขัดเกลาและมาสเตอร์',
                    'ส่งมอบ: แพ็กเกจครบทุกรูปแบบ',
                ],
                'long_description' => 'For those who need complete control over their music. This service offers deep customization options including instrument selection, genre blending, tempo control, and more. Ideal for brand anthems, game soundtracks, or any project requiring unique musical identity.',
                'long_description_th' => 'สำหรับผู้ที่ต้องการควบคุมเพลงอย่างสมบูรณ์ บริการนี้มีตัวเลือกปรับแต่งขั้นสูง รวมถึงการเลือกเครื่องดนตรี ผสมแนวเพลง ควบคุมจังหวะ และอื่นๆ เหมาะสำหรับเพลงประจำแบรนด์ เพลงประกอบเกม หรือโปรเจคที่ต้องการเอกลักษณ์ทางดนตรี',
            ],
            [
                'key' => 'music_album',
                'name' => 'AI Music Album (10 tracks)',
                'name_th' => 'อัลบั้มเพลง AI (10 เพลง)',
                'description' => 'Complete music album with cohesive sound',
                'description_th' => 'อัลบั้มเพลงครบชุดที่มีสไตล์สอดคล้องกัน',
                'price' => 500000,
                'order' => 3,
                'features' => [
                    '10 unique tracks',
                    'Cohesive album concept',
                    'Full commercial rights',
                    'Professional mastering',
                    'Album artwork consultation',
                    'Multiple format delivery (MP3, WAV, FLAC)',
                    'Unlimited revisions per track',
                    'Spotify/Apple Music ready',
                ],
                'features_th' => [
                    '10 เพลงเอกลักษณ์',
                    'แนวคิดอัลบั้มที่สอดคล้องกัน',
                    'ลิขสิทธิ์เชิงพาณิชย์เต็มรูปแบบ',
                    'มาสเตอร์ระดับมืออาชีพ',
                    'ปรึกษาปกอัลบั้ม',
                    'ส่งมอบหลายรูปแบบ (MP3, WAV, FLAC)',
                    'แก้ไขไม่จำกัดต่อเพลง',
                    'พร้อมขึ้น Spotify/Apple Music',
                ],
                'steps' => [
                    'Album Concept: Define overall theme and sound',
                    'Track Planning: Outline each song\'s role',
                    'Batch Generation: Create all tracks with AI',
                    'Review & Refine: Iterative feedback process',
                    'Mastering: Professional audio mastering',
                    'Final Delivery: Complete album package',
                ],
                'steps_th' => [
                    'แนวคิดอัลบั้ม: กำหนดธีมและเสียงโดยรวม',
                    'วางแผนแทร็ก: วางโครงร่างบทบาทแต่ละเพลง',
                    'สร้างเป็นชุด: สร้างทุกแทร็กด้วย AI',
                    'ตรวจสอบและปรับแต่ง: กระบวนการ feedback ซ้ำ',
                    'มาสเตอร์: มาสเตอร์เสียงระดับมืออาชีพ',
                    'ส่งมอบขั้นสุดท้าย: แพ็กเกจอัลบั้มครบชุด',
                ],
                'long_description' => 'Create a complete music album with AI. Perfect for artists, labels, or content creators needing a full-length release. Each track is carefully crafted to contribute to a cohesive listening experience while maintaining individual character.',
                'long_description_th' => 'สร้างอัลบั้มเพลงครบชุดด้วย AI เหมาะสำหรับศิลปิน ค่ายเพลง หรือครีเอเตอร์ที่ต้องการผลงานเต็มรูปแบบ แต่ละเพลงถูกสร้างอย่างพิถีพิถันเพื่อสร้างประสบการณ์การฟังที่สอดคล้องกันพร้อมรักษาเอกลักษณ์ของแต่ละเพลง',
            ],
            [
                'key' => 'music_voice',
                'name' => 'AI Voice Synthesis',
                'name_th' => 'สังเคราะห์เสียงร้อง AI',
                'description' => 'AI-generated vocal tracks',
                'description_th' => 'สร้างแทร็กเสียงร้องด้วย AI',
                'price' => 100000,
                'order' => 4,
                'features' => [
                    'Multiple voice types',
                    'Lyric input support',
                    'Language options (EN, TH, JP, etc.)',
                    'Emotion and style control',
                    'Separate vocal stems',
                    'Pitch and timing adjustment',
                ],
                'features_th' => [
                    'เสียงหลายแบบ',
                    'รองรับเนื้อเพลง',
                    'หลายภาษา (EN, TH, JP ฯลฯ)',
                    'ควบคุมอารมณ์และสไตล์',
                    'แยกแทร็กเสียงร้อง',
                    'ปรับระดับเสียงและจังหวะ',
                ],
                'steps' => [
                    'Voice Selection: Choose vocal character',
                    'Lyric Input: Provide lyrics and melody',
                    'Synthesis: Generate vocal tracks',
                    'Fine-tuning: Adjust emotion and delivery',
                    'Integration: Mix with instrumentals',
                    'Delivery: Final vocal tracks',
                ],
                'steps_th' => [
                    'เลือกเสียง: เลือกตัวละครเสียง',
                    'ใส่เนื้อเพลง: ให้เนื้อเพลงและทำนอง',
                    'สังเคราะห์: สร้างแทร็กเสียงร้อง',
                    'ปรับแต่ง: ปรับอารมณ์และการส่งมอบ',
                    'รวม: มิกซ์กับดนตรีประกอบ',
                    'ส่งมอบ: แทร็กเสียงร้องสุดท้าย',
                ],
                'long_description' => 'Revolutionary AI voice synthesis for songs. Create realistic vocal tracks without a singer. Perfect for demos, complete songs, or experimental projects. Supports multiple languages and vocal styles.',
                'long_description_th' => 'การสังเคราะห์เสียงร้อง AI ที่ล้ำสมัย สร้างแทร็กเสียงร้องที่สมจริงโดยไม่ต้องมีนักร้อง เหมาะสำหรับเดโม เพลงสมบูรณ์ หรือโปรเจคทดลอง รองรับหลายภาษาและสไตล์การร้อง',
            ],
            [
                'key' => 'music_cover',
                'name' => 'AI Music Cover/Remix',
                'name_th' => 'ปรับแต่งเพลงด้วย AI',
                'description' => 'AI-powered music covers and remixes',
                'description_th' => 'ทำคัฟเวอร์และรีมิกซ์ด้วย AI',
                'price' => 60000,
                'order' => 5,
                'features' => [
                    'Style transfer',
                    'Genre transformation',
                    'Tempo and key changes',
                    'Instrument swapping',
                    'AI arrangement',
                ],
                'features_th' => [
                    'เปลี่ยนสไตล์',
                    'แปลงแนวเพลง',
                    'เปลี่ยนจังหวะและคีย์',
                    'สลับเครื่องดนตรี',
                    'เรียบเรียงด้วย AI',
                ],
                'steps' => [
                    'Source Selection: Choose original track',
                    'Style Definition: Define target style',
                    'AI Transformation: Generate new version',
                    'Review: Listen and provide feedback',
                    'Finalization: Polish final version',
                ],
                'steps_th' => [
                    'เลือกต้นฉบับ: เลือกเพลงต้นฉบับ',
                    'กำหนดสไตล์: กำหนดสไตล์เป้าหมาย',
                    'แปลงด้วย AI: สร้างเวอร์ชันใหม่',
                    'ตรวจสอบ: ฟังและให้ feedback',
                    'ปรับแต่งสุดท้าย: ขัดเกลาเวอร์ชันสุดท้าย',
                ],
                'long_description' => 'Transform existing music into new styles. Create covers in different genres, change arrangements, or produce unique remixes. AI analyzes the original and reimagines it according to your specifications.',
                'long_description_th' => 'แปลงเพลงที่มีอยู่เป็นสไตล์ใหม่ สร้างคัฟเวอร์ในแนวเพลงต่างกัน เปลี่ยนการเรียบเรียง หรือทำรีมิกซ์ที่เป็นเอกลักษณ์ AI วิเคราะห์ต้นฉบับและสร้างใหม่ตามที่คุณกำหนด',
            ],
            [
                'key' => 'music_genre',
                'name' => 'Multi-Genre AI Music',
                'name_th' => 'เพลง AI หลายแนว',
                'description' => 'Music spanning multiple genres',
                'description_th' => 'เพลงที่ผสมผสานหลายแนว',
                'price' => 90000,
                'order' => 6,
                'features' => [
                    'Genre fusion capabilities',
                    '5+ different music styles',
                    'Seamless transitions',
                    'Cultural music integration',
                    'Experimental sounds',
                ],
                'features_th' => [
                    'ผสมผสานแนวเพลง',
                    'มากกว่า 5 สไตล์ดนตรี',
                    'เปลี่ยนผ่านอย่างลงตัว',
                    'รวมดนตรีหลายวัฒนธรรม',
                    'เสียงทดลอง',
                ],
                'steps' => [
                    'Genre Selection: Choose genres to blend',
                    'Concept Design: Plan fusion approach',
                    'Generation: Create hybrid tracks',
                    'Balance: Fine-tune genre balance',
                    'Polish: Final mixing and mastering',
                ],
                'steps_th' => [
                    'เลือกแนว: เลือกแนวเพลงที่จะผสม',
                    'ออกแบบแนวคิด: วางแผนการผสมผสาน',
                    'สร้าง: สร้างแทร็กผสม',
                    'สมดุล: ปรับสมดุลแนวเพลง',
                    'ขัดเกลา: มิกซ์และมาสเตอร์สุดท้าย',
                ],
                'long_description' => 'Push musical boundaries with genre-blending AI music. Combine classical with electronic, jazz with hip-hop, or create entirely new fusion styles. Perfect for innovative projects seeking unique sonic identities.',
                'long_description_th' => 'ทำลายขอบเขตดนตรีด้วยเพลง AI ที่ผสมผสานแนว ผสมคลาสสิกกับอิเล็กทรอนิกส์ แจ๊สกับฮิปฮอป หรือสร้างสไตล์ผสมผสานใหม่ๆ เหมาะสำหรับโปรเจคนวัตกรรมที่ต้องการเอกลักษณ์ทางเสียงที่ไม่เหมือนใคร',
            ],
            [
                'key' => 'music_commercial',
                'name' => 'Commercial Music License',
                'name_th' => 'ลิขสิทธิ์เพลงเชิงพาณิชย์',
                'description' => 'Full commercial usage rights',
                'description_th' => 'ลิขสิทธิ์ใช้เชิงพาณิชย์เต็มรูปแบบ',
                'price' => 150000,
                'order' => 7,
                'features' => [
                    'Unlimited commercial use',
                    'Broadcasting rights',
                    'Digital distribution rights',
                    'Advertising usage',
                    'Transfer of copyright',
                    'Legal documentation',
                ],
                'features_th' => [
                    'ใช้เชิงพาณิชย์ไม่จำกัด',
                    'สิทธิ์ออกอากาศ',
                    'สิทธิ์จัดจำหน่ายดิจิทัล',
                    'ใช้ในการโฆษณา',
                    'โอนลิขสิทธิ์',
                    'เอกสารทางกฎหมาย',
                ],
                'steps' => [
                    'License Consultation: Discuss usage needs',
                    'Rights Definition: Define scope of usage',
                    'Legal Documentation: Prepare contracts',
                    'Transfer: Complete rights transfer',
                    'Support: Ongoing licensing support',
                ],
                'steps_th' => [
                    'ปรึกษาลิขสิทธิ์: หารือความต้องการ',
                    'กำหนดสิทธิ์: กำหนดขอบเขตการใช้',
                    'เอกสารกฎหมาย: จัดเตรียมสัญญา',
                    'โอน: โอนสิทธิ์เสร็จสมบูรณ์',
                    'สนับสนุน: สนับสนุนลิขสิทธิ์ต่อเนื่อง',
                ],
                'long_description' => 'Secure full commercial rights for AI-generated music. Includes comprehensive licensing, legal documentation, and transfer of all rights. Perfect for businesses, agencies, and brands requiring complete ownership.',
                'long_description_th' => 'มั่นใจได้กับสิทธิ์เชิงพาณิชย์เต็มรูปแบบสำหรับเพลง AI รวมการออกใบอนุญาตครอบคลุม เอกสารกฎหมาย และโอนสิทธิ์ทั้งหมด เหมาะสำหรับธุรกิจ เอเจนซี่ และแบรนด์ที่ต้องการเป็นเจ้าของเต็มรูปแบบ',
            ],
            [
                'key' => 'music_compose',
                'name' => 'AI Music Composition System',
                'name_th' => 'ระบบแต่งเพลง AI',
                'description' => 'Custom AI music composition platform',
                'description_th' => 'แพลตฟอร์มแต่งเพลง AI แบบกำหนดเอง',
                'price' => 300000,
                'order' => 8,
                'features' => [
                    'Custom AI model training',
                    'Web-based interface',
                    'Real-time generation',
                    'User management system',
                    'API access',
                    'Cloud storage integration',
                    'Export in multiple formats',
                    '1 year technical support',
                ],
                'features_th' => [
                    'ฝึกโมเดล AI แบบกำหนดเอง',
                    'อินเตอร์เฟซบนเว็บ',
                    'สร้างแบบเรียลไทม์',
                    'ระบบจัดการผู้ใช้',
                    'เข้าถึง API',
                    'เชื่อมต่อ Cloud storage',
                    'ส่งออกหลายรูปแบบ',
                    'สนับสนุนทางเทคนิค 1 ปี',
                ],
                'steps' => [
                    'Requirements Analysis: Define system needs',
                    'System Design: Plan architecture and features',
                    'Model Training: Train AI on your music style',
                    'Development: Build web platform',
                    'Testing: Comprehensive quality assurance',
                    'Deployment: Launch and handover',
                    'Training: User training session',
                ],
                'steps_th' => [
                    'วิเคราะห์ความต้องการ: กำหนดความต้องการระบบ',
                    'ออกแบบระบบ: วางแผนสถาปัตยกรรมและฟีเจอร์',
                    'ฝึกโมเดล: ฝึก AI ตามสไตล์เพลงของคุณ',
                    'พัฒนา: สร้างแพลตฟอร์มเว็บ',
                    'ทดสอบ: ตรวจสอบคุณภาพครอบคลุม',
                    'เปิดตัว: เปิดตัวและส่งมอบ',
                    'อบรม: อบรมการใช้งาน',
                ],
                'long_description' => 'Build your own AI music composition platform. Perfect for music companies, game studios, or content agencies needing continuous music production. Includes custom model training, web interface, and API access for integration.',
                'long_description_th' => 'สร้างแพลตฟอร์มแต่งเพลง AI ของคุณเอง เหมาะสำหรับบริษัทเพลง สตูดิโอเกม หรือเอเจนซี่คอนเทนต์ที่ต้องการผลิตเพลงอย่างต่อเนื่อง รวมการฝึกโมเดลแบบกำหนดเอง อินเตอร์เฟซเว็บ และ API สำหรับเชื่อมต่อ',
            ],
            [
                'key' => 'music_mastering',
                'name' => 'AI Audio Mastering',
                'name_th' => 'มาสเตอร์เสียงด้วย AI',
                'description' => 'Professional AI-powered audio mastering',
                'description_th' => 'มาสเตอร์เสียงระดับมืออาชีพด้วย AI',
                'price' => 40000,
                'order' => 9,
                'features' => [
                    'Professional sound quality',
                    'Loudness optimization',
                    'EQ and compression',
                    'Stereo enhancement',
                    'Before/after comparison',
                    'Multiple output formats',
                ],
                'features_th' => [
                    'คุณภาพเสียงระดับมืออาชีพ',
                    'ปรับความดังให้เหมาะสม',
                    'EQ และ compression',
                    'ปรับปรุง stereo',
                    'เปรียบเทียบก่อน/หลัง',
                    'ส่งออกหลายรูปแบบ',
                ],
                'steps' => [
                    'Upload: Submit your audio files',
                    'Analysis: AI analyzes audio characteristics',
                    'Processing: Apply mastering techniques',
                    'Preview: Review before/after',
                    'Adjustment: Fine-tune if needed',
                    'Download: Get mastered files',
                ],
                'steps_th' => [
                    'อัพโหลด: ส่งไฟล์เสียงของคุณ',
                    'วิเคราะห์: AI วิเคราะห์ลักษณะเสียง',
                    'ประมวลผล: ใช้เทคนิคมาสเตอร์',
                    'ดูตัวอย่าง: ตรวจสอบก่อน/หลัง',
                    'ปรับแต่ง: ปรับแต่งถ้าจำเป็น',
                    'ดาวน์โหลด: รับไฟล์ที่มาสเตอร์แล้ว',
                ],
                'long_description' => 'Professional audio mastering using advanced AI algorithms. Make your tracks radio-ready with optimized loudness, clarity, and professional sound quality. Perfect for musicians, podcasters, and content creators.',
                'long_description_th' => 'มาสเตอร์เสียงระดับมืออาชีพด้วยอัลกอริทึม AI ขั้นสูง ทำให้แทร์กของคุณพร้อมออกอากาศด้วยความดังที่เหมาะสม ความชัดเจน และคุณภาพเสียงระดับมืออาชีพ เหมาะสำหรับนักดนตรี พอดแคสเตอร์ และครีเอเตอร์',
            ],
            [
                'key' => 'music_stem',
                'name' => 'AI Stem Separation',
                'name_th' => 'แยกแทร็กเพลงด้วย AI',
                'description' => 'Separate music into individual tracks',
                'description_th' => 'แยกเพลงออกเป็นแทร็กแต่ละอย่าง',
                'price' => 35000,
                'order' => 10,
                'features' => [
                    'Vocals extraction',
                    'Drums isolation',
                    'Bass separation',
                    'Instruments separation',
                    'High-quality stems',
                    'Multiple export formats',
                ],
                'features_th' => [
                    'แยกเสียงร้อง',
                    'แยกกลอง',
                    'แยกเบส',
                    'แยกเครื่องดนตรี',
                    'แทร็กคุณภาพสูง',
                    'ส่งออกหลายรูปแบบ',
                ],
                'steps' => [
                    'Upload: Provide audio file',
                    'Analysis: AI identifies components',
                    'Separation: Extract individual stems',
                    'Quality Check: Verify separation quality',
                    'Delivery: Receive all stems',
                ],
                'steps_th' => [
                    'อัพโหลด: ให้ไฟล์เสียง',
                    'วิเคราะห์: AI ระบุส่วนประกอบ',
                    'แยก: แยกแทร็กแต่ละอย่าง',
                    'ตรวจสอบ: ตรวจคุณภาพการแยก',
                    'ส่งมอบ: รับแทร็กทั้งหมด',
                ],
                'long_description' => 'Advanced AI stem separation technology to extract individual instruments and vocals from mixed audio. Perfect for remixing, sampling, karaoke creation, or music production. High-quality separation with minimal artifacts.',
                'long_description_th' => 'เทคโนโลยีแยกแทร็กด้วย AI ขั้นสูงเพื่อแยกเครื่องดนตรีและเสียงร้องจากเสียงที่มิกซ์แล้ว เหมาะสำหรับรีมิกซ์ แซมปลิ้ง สร้างคาราโอเกะ หรือการผลิตเพลง การแยกคุณภาพสูงพร้อมสิ่งแปลกปลอมน้อยที่สุด',
            ],
        ];

        foreach ($musicOptions as $option) {
            QuotationOption::create(array_merge($option, ['quotation_category_id' => $musicAi->id]));
        }

        // AI Image Generation
        $aiImage = QuotationCategory::create([
            'key' => 'ai_image',
            'name' => 'AI Image Generation',
            'name_th' => 'สร้างภาพด้วย AI',
            'icon' => '🎨',
            'description' => 'Advanced AI image generation and editing services',
            'description_th' => 'บริการสร้างและแก้ไขภาพด้วย AI',
            'order' => 2,
            'is_active' => true,
        ]);

        $imageOptions = [
            [
                'key' => 'gen_image',
                'name' => 'AI Image Generation',
                'name_th' => 'สร้างภาพด้วย AI',
                'description' => 'Create stunning images from text descriptions',
                'description_th' => 'สร้างภาพสวยงามจากคำอธิบาย',
                'price' => 80000,
                'order' => 1,
                'features' => [
                    'High-resolution outputs (up to 4K)',
                    'Multiple style options',
                    'Commercial usage rights',
                    'Unlimited revisions',
                    'Fast turnaround (24-48 hours)',
                    '50+ images per project',
                ],
                'features_th' => [
                    'ความละเอียดสูง (สูงสุด 4K)',
                    'หลายสไตล์',
                    'ลิขสิทธิ์เชิงพาณิชย์',
                    'แก้ไขไม่จำกัด',
                    'ส่งมอบเร็ว (24-48 ชั่วโมง)',
                    'มากกว่า 50 ภาพต่อโปรเจค',
                ],
                'steps' => [
                    'Brief: Describe your vision',
                    'Generation: AI creates initial images',
                    'Selection: Choose favorites',
                    'Refinement: Adjust and perfect',
                    'Delivery: Receive final images',
                ],
                'steps_th' => [
                    'สรุปข้อมูล: อธิบายวิสัยทัศน์ของคุณ',
                    'สร้าง: AI สร้างภาพเบื้องต้น',
                    'เลือก: เลือกภาพที่ชอบ',
                    'ปรับแต่ง: ปรับและทำให้สมบูรณ์',
                    'ส่งมอบ: รับภาพสุดท้าย',
                ],
                'long_description' => 'Transform your ideas into stunning visuals with advanced AI image generation. Perfect for marketing materials, social media content, product visualizations, or any creative project requiring unique imagery.',
                'long_description_th' => 'แปลงไอเดียของคุณเป็นภาพที่สวยงามด้วยการสร้างภาพ AI ขั้นสูง เหมาะสำหรับสื่อการตลาด คอนเทนต์โซเชียลมีเดีย การแสดงภาพผลิตภัณฑ์ หรือโปรเจคสร้างสรรค์ที่ต้องการภาพเอกลักษณ์',
            ],
            [
                'key' => 'gen_video',
                'name' => 'AI Video Generation',
                'name_th' => 'สร้างวิดีโอด้วย AI',
                'description' => 'Generate videos from text or images',
                'description_th' => 'สร้างวิดีโอจากข้อความหรือภาพ',
                'price' => 150000,
                'order' => 2,
                'features' => [
                    'Text-to-video generation',
                    'Image-to-video animation',
                    'Up to 2 minutes duration',
                    'HD quality (1080p)',
                    'Custom transitions',
                    'Background music integration',
                    'Subtitle support',
                ],
                'features_th' => [
                    'สร้างวิดีโอจากข้อความ',
                    'แอนิเมชันภาพเป็นวิดีโอ',
                    'ความยาวสูงสุด 2 นาที',
                    'คุณภาพ HD (1080p)',
                    'เปลี่ยนผ่านแบบกำหนดเอง',
                    'รวมเพลงประกอบ',
                    'รองรับคำบรรยาย',
                ],
                'steps' => [
                    'Concept: Define video concept',
                    'Storyboard: Plan video flow',
                    'Generation: Create video clips',
                    'Assembly: Combine and edit',
                    'Review: Feedback and adjustments',
                    'Final Export: Deliver video',
                ],
                'steps_th' => [
                    'แนวคิด: กำหนดแนวคิดวิดีโอ',
                    'สตอรี่บอร์ด: วางแผนการไหลของวิดีโอ',
                    'สร้าง: สร้างคลิปวิดีโอ',
                    'ประกอบ: รวมและตัดต่อ',
                    'ตรวจสอบ: feedback และปรับแต่ง',
                    'ส่งออกขั้นสุดท้าย: ส่งมอบวิดีโอ',
                ],
                'long_description' => 'Create engaging videos using AI. Transform text descriptions or static images into dynamic video content. Perfect for social media, advertising, presentations, or any project requiring video content.',
                'long_description_th' => 'สร้างวิดีโอที่น่าสนใจด้วย AI แปลงคำอธิบายหรือภาพนิ่งเป็นวิดีโอไดนามิก เหมาะสำหรับโซเชียลมีเดีย การโฆษณา งานนำเสนอ หรือโปรเจคที่ต้องการคอนเทนต์วิดีโอ',
            ],
            [
                'key' => 'gen_text',
                'name' => 'AI Content Writing',
                'name_th' => 'เขียนเนื้อหาด้วย AI',
                'description' => 'Professional content creation with AI',
                'description_th' => 'สร้างเนื้อหาระดับมืออาชีพด้วย AI',
                'price' => 60000,
                'order' => 3,
                'features' => [
                    'Blog posts & articles',
                    'Product descriptions',
                    'Social media content',
                    'SEO optimization',
                    'Multiple language support',
                    'Tone and style customization',
                    'Unlimited revisions',
                ],
                'features_th' => [
                    'โพสต์บล็อกและบทความ',
                    'คำอธิบายผลิตภัณฑ์',
                    'เนื้อหาโซเชียลมีเดีย',
                    'ปรับแต่ง SEO',
                    'รองรับหลายภาษา',
                    'ปรับแต่งโทนและสไตล์',
                    'แก้ไขไม่จำกัด',
                ],
                'steps' => [
                    'Brief: Provide content requirements',
                    'Research: AI gathers information',
                    'Generation: Create content drafts',
                    'Review: You provide feedback',
                    'Refinement: Polish content',
                    'Delivery: Final content package',
                ],
                'steps_th' => [
                    'สรุปข้อมูล: ให้ข้อกำหนดเนื้อหา',
                    'วิจัย: AI รวบรวมข้อมูล',
                    'สร้าง: สร้างร่างเนื้อหา',
                    'ตรวจสอบ: คุณให้ feedback',
                    'ปรับปรุง: ขัดเกลาเนื้อหา',
                    'ส่งมอบ: แพ็กเกจเนื้อหาสุดท้าย',
                ],
                'long_description' => 'Professional content creation powered by AI. Generate blog posts, articles, product descriptions, and marketing copy that engages your audience. SEO-optimized and tailored to your brand voice.',
                'long_description_th' => 'สร้างเนื้อหาระดับมืออาชีพด้วย AI สร้างโพสต์บล็อก บทความ คำอธิบายผลิตภัณฑ์ และคำโฆษณาที่ดึงดูดผู้ชม ปรับแต่ง SEO และเหมาะกับเสียงแบรนด์ของคุณ',
            ],
            [
                'key' => 'gen_avatar',
                'name' => 'AI Avatar/Character',
                'name_th' => 'สร้าง Avatar ด้วย AI',
                'description' => 'Create unique digital avatars and characters',
                'description_th' => 'สร้าง avatar และตัวละครดิจิทัลที่เป็นเอกลักษณ์',
                'price' => 100000,
                'order' => 4,
                'features' => [
                    'Custom character design',
                    'Multiple poses and expressions',
                    'High-resolution exports',
                    '360-degree views',
                    'Animation-ready rigging',
                    'VRM format support',
                    'Commercial license included',
                ],
                'features_th' => [
                    'ออกแบบตัวละครแบบกำหนดเอง',
                    'หลายท่าทางและสีหน้า',
                    'ส่งออกความละเอียดสูง',
                    'มุมมอง 360 องศา',
                    'พร้อมสำหรับแอนิเมชัน',
                    'รองรับรูปแบบ VRM',
                    'รวมลิขสิทธิ์เชิงพาณิชย์',
                ],
                'steps' => [
                    'Concept: Describe character concept',
                    'Generation: AI creates character designs',
                    'Selection: Choose preferred design',
                    'Refinement: Adjust details',
                    'Rigging: Prepare for animation (optional)',
                    'Delivery: Final character assets',
                ],
                'steps_th' => [
                    'แนวคิด: อธิบายแนวคิดตัวละคร',
                    'สร้าง: AI สร้างการออกแบบตัวละคร',
                    'เลือก: เลือกการออกแบบที่ต้องการ',
                    'ปรับแต่ง: ปรับรายละเอียด',
                    'Rigging: เตรียมสำหรับแอนิเมชัน (ตัวเลือก)',
                    'ส่งมอบ: ไฟล์ตัวละครสุดท้าย',
                ],
                'long_description' => 'Create unique digital avatars and characters for VTubing, gaming, metaverse applications, or brand mascots. AI-powered character generation with full customization options and animation-ready outputs.',
                'long_description_th' => 'สร้าง avatar และตัวละครดิจิทัลที่เป็นเอกลักษณ์สำหรับ VTubing เกม แอปพลิเคชัน metaverse หรือมาสคอตแบรนด์ การสร้างตัวละครด้วย AI พร้อมตัวเลือกปรับแต่งครบถ้วนและผลลัพธ์พร้อมแอนิเมชัน',
            ],
        ];

        foreach ($imageOptions as $option) {
            QuotationOption::create(array_merge($option, ['quotation_category_id' => $aiImage->id]));
        }

        // AI Chatbot
        $chatbot = QuotationCategory::create([
            'key' => 'ai_chatbot',
            'name' => 'AI Chatbot',
            'name_th' => 'Chatbot อัจฉริยะ',
            'icon' => '💬',
            'description' => 'Intelligent chatbot solutions powered by AI',
            'description_th' => 'โซลูชัน Chatbot อัจฉริยะด้วย AI',
            'order' => 3,
            'is_active' => true,
        ]);

        $chatbotOptions = [
            [
                'key' => 'chat_basic',
                'name' => 'Basic Chatbot',
                'name_th' => 'Chatbot พื้นฐาน',
                'description' => 'Simple rule-based chatbot',
                'description_th' => 'Chatbot แบบกฎเกณฑ์พื้นฐาน',
                'price' => 50000,
                'order' => 1,
                'features' => [
                    'Rule-based responses',
                    'FAQ automation',
                    'Multi-language support',
                    'Web widget integration',
                    'Basic analytics',
                    '3 months support',
                ],
                'features_th' => [
                    'ตอบกลับตามกฎเกณฑ์',
                    'ระบบ FAQ อัตโนมัติ',
                    'รองรับหลายภาษา',
                    'ติดตั้งบนเว็บไซต์',
                    'สถิติพื้นฐาน',
                    'สนับสนุน 3 เดือน',
                ],
                'steps' => [
                    'Requirements: Define bot purpose',
                    'Script: Create conversation flows',
                    'Development: Build chatbot',
                    'Testing: QA and refinement',
                    'Deployment: Launch on platform',
                    'Training: User guide delivery',
                ],
                'steps_th' => [
                    'ความต้องการ: กำหนดวัตถุประสงค์บอท',
                    'สคริปต์: สร้างการไหลของบทสนทนา',
                    'พัฒนา: สร้าง chatbot',
                    'ทดสอบ: ตรวจสอบและปรับแต่ง',
                    'เปิดตัว: เปิดตัวบนแพลตฟอร์ม',
                    'อบรม: ส่งมอบคู่มือผู้ใช้',
                ],
                'long_description' => 'Perfect for small businesses needing automated customer support. Handles frequently asked questions, basic inquiries, and common requests. Easy to maintain and update.',
                'long_description_th' => 'เหมาะสำหรับธุรกิจขนาดเล็กที่ต้องการระบบสนับสนุนลูกค้าอัตโนมัติ จัดการคำถามที่พบบ่อย คำถามพื้นฐาน และคำขอทั่วไป ง่ายต่อการบำรุงรักษาและอัพเดท',
            ],
            [
                'key' => 'chat_gpt',
                'name' => 'GPT-powered Chatbot',
                'name_th' => 'Chatbot ด้วย GPT',
                'description' => 'Advanced AI chatbot with natural conversations',
                'description_th' => 'Chatbot AI ขั้นสูงพร้อมการสนทนาธรรมชาติ',
                'price' => 100000,
                'order' => 2,
                'features' => [
                    'GPT-4 powered',
                    'Natural language understanding',
                    'Context-aware responses',
                    'Personality customization',
                    'Integration with databases',
                    'Advanced analytics',
                    '6 months support',
                    'API access',
                ],
                'features_th' => [
                    'ขับเคลื่อนด้วย GPT-4',
                    'เข้าใจภาษาธรรมชาติ',
                    'ตอบกลับตามบริบท',
                    'ปรับแต่งบุคลิกภาพ',
                    'เชื่อมต่อฐานข้อมูล',
                    'สถิติขั้นสูง',
                    'สนับสนุน 6 เดือน',
                    'เข้าถึง API',
                ],
                'steps' => [
                    'Discovery: Understand business needs',
                    'Design: Plan conversation personality',
                    'Training: Feed domain knowledge',
                    'Development: Build and integrate',
                    'Testing: Extensive testing phase',
                    'Launch: Deploy to production',
                    'Optimization: Monitor and improve',
                ],
                'steps_th' => [
                    'ค้นพบ: เข้าใจความต้องการธุรกิจ',
                    'ออกแบบ: วางแผนบุคลิกภาพการสนทนา',
                    'ฝึก: ป้อนความรู้เฉพาะทาง',
                    'พัฒนา: สร้างและเชื่อมต่อ',
                    'ทดสอบ: ระยะทดสอบอย่างละเอียด',
                    'เปิดตัว: เปิดใช้งาน',
                    'ปรับแต่ง: ติดตามและปรับปรุง',
                ],
                'long_description' => 'Enterprise-grade chatbot powered by GPT-4. Understands complex queries, maintains context, and provides human-like responses. Perfect for customer service, sales, and support automation.',
                'long_description_th' => 'Chatbot ระดับองค์กรขับเคลื่อนด้วย GPT-4 เข้าใจคำถามที่ซับซ้อน รักษาบริบท และให้การตอบกลับที่เหมือนมนุษย์ เหมาะสำหรับการบริการลูกค้า การขาย และระบบสนับสนุนอัตโนมัติ',
            ],
            [
                'key' => 'chat_voice',
                'name' => 'Voice Assistant',
                'name_th' => 'ผู้ช่วยเสียง AI',
                'description' => 'Voice-enabled AI assistant',
                'description_th' => 'ผู้ช่วย AI แบบเสียง',
                'price' => 120000,
                'order' => 3,
                'features' => [
                    'Speech-to-text',
                    'Text-to-speech',
                    'Multi-language support',
                    'Voice customization',
                    'Hands-free operation',
                    'Mobile app ready',
                    'Wake word detection',
                ],
                'features_th' => [
                    'แปลงเสียงเป็นข้อความ',
                    'แปลงข้อความเป็นเสียง',
                    'รองรับหลายภาษา',
                    'ปรับแต่งเสียง',
                    'ใช้งานแบบแฮนด์ฟรี',
                    'พร้อมแอปมือถือ',
                    'ตรวจจับคำปลุก',
                ],
                'steps' => [
                    'Requirements: Define voice assistant scope',
                    'Voice Design: Choose voice characteristics',
                    'Development: Build voice recognition',
                    'Integration: Connect with services',
                    'Testing: Voice accuracy testing',
                    'Deployment: Launch assistant',
                ],
                'steps_th' => [
                    'ความต้องการ: กำหนดขอบเขตผู้ช่วยเสียง',
                    'ออกแบบเสียง: เลือกลักษณะเสียง',
                    'พัฒนา: สร้างระบบรู้จำเสียง',
                    'เชื่อมต่อ: เชื่อมต่อกับบริการ',
                    'ทดสอบ: ทดสอบความแม่นยำของเสียง',
                    'เปิดตัว: เปิดตัวผู้ช่วย',
                ],
                'long_description' => 'Voice-enabled AI assistant for hands-free interaction. Perfect for smart home systems, automotive applications, accessibility features, or any scenario requiring voice control.',
                'long_description_th' => 'ผู้ช่วย AI แบบเสียงสำหรับการโต้ตอบแบบแฮนด์ฟรี เหมาะสำหรับระบบสมาร์ทโฮม แอปพลิเคชันยานยนต์ ฟีเจอร์การเข้าถึง หรือสถานการณ์ใดๆ ที่ต้องการควบคุมด้วยเสียง',
            ],
            [
                'key' => 'chat_multi',
                'name' => 'Multi-channel Bot',
                'name_th' => 'Bot หลายช่องทาง',
                'description' => 'Unified bot across multiple platforms',
                'description_th' => 'บอทรวมหลายแพลตฟอร์ม',
                'price' => 150000,
                'order' => 4,
                'features' => [
                    'Website integration',
                    'LINE Official integration',
                    'Facebook Messenger',
                    'Instagram DM',
                    'WhatsApp Business',
                    'Unified dashboard',
                    'Cross-platform analytics',
                    '1 year support',
                ],
                'features_th' => [
                    'ติดตั้งบนเว็บไซต์',
                    'เชื่อมต่อ LINE Official',
                    'Facebook Messenger',
                    'Instagram DM',
                    'WhatsApp Business',
                    'แดชบอร์ดรวม',
                    'สถิติข้ามแพลตฟอร์ม',
                    'สนับสนุน 1 ปี',
                ],
                'steps' => [
                    'Platform Selection: Choose channels',
                    'Design: Create unified experience',
                    'Development: Build integrations',
                    'Testing: Test all platforms',
                    'Launch: Deploy across channels',
                    'Monitoring: Track performance',
                ],
                'steps_th' => [
                    'เลือกแพลตฟอร์ม: เลือกช่องทาง',
                    'ออกแบบ: สร้างประสบการณ์รวม',
                    'พัฒนา: สร้างการเชื่อมต่อ',
                    'ทดสอบ: ทดสอบทุกแพลตฟอร์ม',
                    'เปิดตัว: เปิดใช้งานทุกช่องทาง',
                    'ติดตาม: ติดตามประสิทธิภาพ',
                ],
                'long_description' => 'Reach customers wherever they are. Single bot deployed across multiple messaging platforms with unified management. Consistent experience and centralized analytics.',
                'long_description_th' => 'เข้าถึงลูกค้าทุกที่ที่พวกเขาอยู่ บอทเดียวเปิดใช้งานบนหลายแพลตฟอร์มข้อความพร้อมการจัดการรวม ประสบการณ์สม่ำเสมอและสถิติรวมศูนย์',
            ],
            [
                'key' => 'chat_custom',
                'name' => 'Custom AI Agent',
                'name_th' => 'AI Agent แบบกำหนดเอง',
                'description' => 'Fully customized AI agent with advanced capabilities',
                'description_th' => 'AI Agent แบบกำหนดเองพร้อมความสามารถขั้นสูง',
                'price' => 200000,
                'order' => 5,
                'features' => [
                    'Custom AI model',
                    'Task automation',
                    'API integrations',
                    'Database access',
                    'Custom workflows',
                    'Advanced NLP',
                    'Self-learning capabilities',
                    'Enterprise support',
                ],
                'features_th' => [
                    'โมเดล AI แบบกำหนดเอง',
                    'ระบบอัตโนมัติ',
                    'เชื่อมต่อ API',
                    'เข้าถึงฐานข้อมูล',
                    'workflow แบบกำหนดเอง',
                    'NLP ขั้นสูง',
                    'ความสามารถเรียนรู้เอง',
                    'สนับสนุนระดับองค์กร',
                ],
                'steps' => [
                    'Analysis: Deep dive into requirements',
                    'Architecture: Design custom solution',
                    'Model Training: Train specialized AI',
                    'Development: Build custom agent',
                    'Integration: Connect all systems',
                    'Testing: Comprehensive testing',
                    'Deployment: Launch to production',
                    'Optimization: Continuous improvement',
                ],
                'steps_th' => [
                    'วิเคราะห์: ศึกษาความต้องการอย่างลึก',
                    'สถาปัตยกรรม: ออกแบบโซลูชันแบบกำหนดเอง',
                    'ฝึกโมเดล: ฝึก AI เฉพาะทาง',
                    'พัฒนา: สร้าง agent แบบกำหนดเอง',
                    'เชื่อมต่อ: เชื่อมต่อทุกระบบ',
                    'ทดสอบ: ทดสอบครอบคลุม',
                    'เปิดตัว: เปิดใช้งาน',
                    'ปรับแต่ง: ปรับปรุงอย่างต่อเนื่อง',
                ],
                'long_description' => 'Enterprise-level custom AI agent tailored to your specific needs. Can automate complex workflows, integrate with existing systems, and perform specialized tasks. Includes custom model training and ongoing optimization.',
                'long_description_th' => 'AI agent แบบกำหนดเองระดับองค์กรที่ปรับแต่งตามความต้องการเฉพาะของคุณ สามารถทำระบบอัตโนมัติ workflow ที่ซับซ้อน เชื่อมต่อกับระบบที่มีอยู่ และทำงานเฉพาะทาง รวมการฝึกโมเดลแบบกำหนดเองและการปรับแต่งอย่างต่อเนื่อง',
            ],
        ];

        foreach ($chatbotOptions as $option) {
            QuotationOption::create(array_merge($option, ['quotation_category_id' => $chatbot->id]));
        }

        $this->command->info('Quotation categories and options seeded with full details!');
    }
}
