<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $now = now();

        // Seed categories
        DB::table('bt_categories')->insert([
            [
                'name' => 'หนัง/ซีรีส์',
                'slug' => 'movies',
                'icon' => 'movie',
                'description' => 'ภาพยนตร์และซีรีส์',
                'is_adult' => false,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'เพลง',
                'slug' => 'music',
                'icon' => 'music_note',
                'description' => 'เพลงและอัลบั้ม',
                'is_adult' => false,
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'เกม',
                'slug' => 'games',
                'icon' => 'sports_esports',
                'description' => 'เกมและม็อด',
                'is_adult' => false,
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'แอพพลิเคชัน',
                'slug' => 'apps',
                'icon' => 'apps',
                'description' => 'แอพมือถือและเดสก์ท็อป',
                'is_adult' => false,
                'sort_order' => 4,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'หนังสือ/เอกสาร',
                'slug' => 'books',
                'icon' => 'menu_book',
                'description' => 'หนังสือและเอกสาร',
                'is_adult' => false,
                'sort_order' => 5,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'รูปภาพ',
                'slug' => 'images',
                'icon' => 'image',
                'description' => 'รูปภาพและกราฟิก',
                'is_adult' => false,
                'sort_order' => 6,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ซอฟต์แวร์',
                'slug' => 'software',
                'icon' => 'computer',
                'description' => 'ซอฟต์แวร์และเครื่องมือ',
                'is_adult' => false,
                'sort_order' => 7,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'การศึกษา',
                'slug' => 'education',
                'icon' => 'school',
                'description' => 'สื่อการเรียนรู้',
                'is_adult' => false,
                'sort_order' => 8,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'อื่นๆ',
                'slug' => 'other',
                'icon' => 'folder',
                'description' => 'ไฟล์ทั่วไป',
                'is_adult' => false,
                'sort_order' => 9,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => '18+',
                'slug' => 'adult',
                'icon' => '18_up_rating',
                'description' => 'เนื้อหาสำหรับผู้ใหญ่',
                'is_adult' => true,
                'sort_order' => 10,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // Seed trophies
        DB::table('bt_trophies')->insert([
            // === Easy (7) ===
            [
                'slug' => 'newcomer',
                'name' => 'ผู้เริ่มต้น',
                'description' => 'สมัครใช้งานสำเร็จ',
                'icon' => '🌱',
                'badge_text' => '🌱',
                'difficulty' => 'easy',
                'requirement_type' => 'account_created',
                'requirement_value' => 1,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'first_share',
                'name' => 'นักแชร์มือใหม่',
                'description' => 'อัพโหลดไฟล์แรกสำเร็จ',
                'icon' => '📤',
                'badge_text' => '📤',
                'difficulty' => 'easy',
                'requirement_type' => 'files_shared',
                'requirement_value' => 1,
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'first_download',
                'name' => 'นักดาวน์โหลด',
                'description' => 'ดาวน์โหลดไฟล์แรกสำเร็จ',
                'icon' => '📥',
                'badge_text' => '📥',
                'difficulty' => 'easy',
                'requirement_type' => 'files_downloaded',
                'requirement_value' => 1,
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'network_creator',
                'name' => 'สร้างเครือข่าย',
                'description' => 'สร้างเครือข่ายแรก',
                'icon' => '🌐',
                'badge_text' => '🌐',
                'difficulty' => 'easy',
                'requirement_type' => 'networks_created',
                'requirement_value' => 1,
                'sort_order' => 4,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'social',
                'name' => 'สังคมออนไลน์',
                'description' => 'เข้าร่วมเครือข่าย 3 แห่ง',
                'icon' => '👥',
                'badge_text' => '👥',
                'difficulty' => 'easy',
                'requirement_type' => 'networks_joined',
                'requirement_value' => 3,
                'sort_order' => 5,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'first_seed',
                'name' => 'Seeder มือใหม่',
                'description' => 'Seed ไฟล์ให้คนอื่นสำเร็จ',
                'icon' => '🌾',
                'badge_text' => '🌾',
                'difficulty' => 'easy',
                'requirement_type' => 'seed_count',
                'requirement_value' => 1,
                'sort_order' => 6,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'explorer',
                'name' => 'นักสำรวจ',
                'description' => 'ดาวน์โหลดจาก 3 หมวดหมู่',
                'icon' => '🧭',
                'badge_text' => '🧭',
                'difficulty' => 'easy',
                'requirement_type' => 'categories_downloaded',
                'requirement_value' => 3,
                'sort_order' => 7,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // === Medium (7) ===
            [
                'slug' => 'active_sharer',
                'name' => 'นักแชร์ขยัน',
                'description' => 'อัพโหลด 10 ไฟล์',
                'icon' => '📦',
                'badge_text' => '📦',
                'difficulty' => 'medium',
                'requirement_type' => 'files_shared',
                'requirement_value' => 10,
                'sort_order' => 8,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'dedicated_seeder',
                'name' => 'Seeder ตัวยง',
                'description' => 'Seed ไฟล์รวม 24 ชั่วโมง',
                'icon' => '🔄',
                'badge_text' => '🔄',
                'difficulty' => 'medium',
                'requirement_type' => 'seed_hours',
                'requirement_value' => 24,
                'sort_order' => 9,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'data_contributor',
                'name' => 'จัดเต็ม',
                'description' => 'อัพโหลดรวม 1 GB',
                'icon' => '💾',
                'badge_text' => '💾',
                'difficulty' => 'medium',
                'requirement_type' => 'uploaded_gb',
                'requirement_value' => 1,
                'sort_order' => 10,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'popular',
                'name' => 'ได้รับความนิยม',
                'description' => 'ไฟล์ถูกดาวน์โหลด 50 ครั้ง',
                'icon' => '⭐',
                'badge_text' => '⭐',
                'difficulty' => 'medium',
                'requirement_type' => 'total_downloads_received',
                'requirement_value' => 50,
                'sort_order' => 11,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'top_ten',
                'name' => 'Top 10',
                'description' => 'ติดอันดับ Top 10',
                'icon' => '🏆',
                'badge_text' => '🏆',
                'difficulty' => 'medium',
                'requirement_type' => 'rank_position',
                'requirement_value' => 10,
                'sort_order' => 12,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'diversified',
                'name' => 'หลากหลาย',
                'description' => 'อัพโหลดใน 5 หมวดหมู่',
                'icon' => '🎯',
                'badge_text' => '🎯',
                'difficulty' => 'medium',
                'requirement_type' => 'categories_shared',
                'requirement_value' => 5,
                'sort_order' => 13,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'helper',
                'name' => 'ผู้ช่วยเหลือ',
                'description' => 'Seed ให้คน 20 คน',
                'icon' => '🤝',
                'badge_text' => '🤝',
                'difficulty' => 'medium',
                'requirement_type' => 'unique_peers_seeded',
                'requirement_value' => 20,
                'sort_order' => 14,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // === Hard (6) ===
            [
                'slug' => 'legend',
                'name' => 'ตำนาน',
                'description' => 'อัพโหลด 100 ไฟล์',
                'icon' => '💎',
                'badge_text' => '💎',
                'difficulty' => 'hard',
                'requirement_type' => 'files_shared',
                'requirement_value' => 100,
                'sort_order' => 15,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'seed_god',
                'name' => 'เทพแห่ง Seed',
                'description' => 'Seed ไฟล์รวม 168 ชั่วโมง (7 วัน)',
                'icon' => '🔥',
                'badge_text' => '🔥',
                'difficulty' => 'hard',
                'requirement_type' => 'seed_hours',
                'requirement_value' => 168,
                'sort_order' => 16,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'champion',
                'name' => 'แชมป์',
                'description' => 'ครองอันดับ 1 นาน 7 วัน',
                'icon' => '👑',
                'badge_text' => '👑',
                'difficulty' => 'hard',
                'requirement_type' => 'days_at_rank_1',
                'requirement_value' => 7,
                'sort_order' => 17,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'superstar',
                'name' => 'ดาวเด่น',
                'description' => 'ไฟล์ถูกดาวน์โหลด 500 ครั้ง',
                'icon' => '🌟',
                'badge_text' => '🌟',
                'difficulty' => 'hard',
                'requirement_type' => 'total_downloads_received',
                'requirement_value' => 500,
                'sort_order' => 18,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'upload_king',
                'name' => 'จอมอัพโหลด',
                'description' => 'อัพโหลดรวม 10 GB',
                'icon' => '💪',
                'badge_text' => '💪',
                'difficulty' => 'hard',
                'requirement_type' => 'uploaded_gb',
                'requirement_value' => 10,
                'sort_order' => 19,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'guardian',
                'name' => 'ผู้พิทักษ์',
                'description' => 'รักษา Seed Ratio > 2.0 นาน 30 วัน',
                'icon' => '🏅',
                'badge_text' => '🏅',
                'difficulty' => 'hard',
                'requirement_type' => 'seed_ratio_days',
                'requirement_value' => 30,
                'sort_order' => 20,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }

    public function down(): void
    {
        DB::table('bt_trophies')->truncate();
        DB::table('bt_categories')->truncate();
    }
};
