<?php

/*
|--------------------------------------------------------------------------
| Registrant (WHOIS) rules, per country
|--------------------------------------------------------------------------
|
| What the registrar accepts in a WHOIS profile. Its API reference documents
| `whois_details` as a bare object, so every rule here was read back from the
| registrar's own 422 answers on 2026-10-09 (payloads carrying a deliberately
| invalid e-mail, so nothing was created):
|
|   - the region and postcode keys are per country: `state_th` / `zip_th`,
|     `state_us` / `zip_us` ... and Hong Kong alone takes `zip_general`
|   - the region must be one of the values listed below, spelled exactly
|   - `address` is ONE line of at most 50 characters, with at least one digit
|     and one letter and none of  ~ ! @ # $ % ^ & * ` + _ = ( ) | / \ ' " [ ] { } ° º
|   - `city` refuses the same set plus < > . -  (at most 64 characters)
|   - names: letters only (Thai is fine), 2-64 characters, a hyphen allowed
|   - `phone_cc` and `phone_number` are digits only: no "+", no dashes
|
| The registrant form, its validation and App\Support\WhoisContact all read
| from here, so a country added below is offered everywhere at once.
| Region keys are the registrar's values; the label is what the customer reads.
|
*/

return [
    'countries' => [
        'TH' => [
            'name' => ['th' => 'ไทย', 'en' => 'Thailand'],
            'phone_cc' => '66',
            'state_key' => 'state_th',
            'state_label' => ['th' => 'จังหวัด', 'en' => 'Province'],
            'zip_key' => 'zip_th',
            'zip_pattern' => '/^\\d{5}$/',
            'zip_example' => '10110',
            'regions' => [
                'Bangkok' => 'กรุงเทพมหานคร',
                'Krabi' => 'กระบี่',
                'Kanchanaburi' => 'กาญจนบุรี',
                'Kalasin' => 'กาฬสินธุ์',
                'Kamphaeng Phet' => 'กำแพงเพชร',
                'Khon Kaen' => 'ขอนแก่น',
                'Chanthaburi' => 'จันทบุรี',
                'Chachoengsao' => 'ฉะเชิงเทรา',
                'Chonburi' => 'ชลบุรี',
                'Chai Nat' => 'ชัยนาท',
                'Chaiyaphum' => 'ชัยภูมิ',
                'Chumphon' => 'ชุมพร',
                'Chiang Rai' => 'เชียงราย',
                'Chiang Mai' => 'เชียงใหม่',
                'Trang' => 'ตรัง',
                'Trat' => 'ตราด',
                'Tak' => 'ตาก',
                'Nakhon Nayok' => 'นครนายก',
                'Nakhon Pathom' => 'นครปฐม',
                'Nakhon Phanom' => 'นครพนม',
                'Nakhon Ratchasima' => 'นครราชสีมา',
                'Nakhon Si Thammarat' => 'นครศรีธรรมราช',
                'Nakhon Sawan' => 'นครสวรรค์',
                'Nonthaburi' => 'นนทบุรี',
                'Narathiwat' => 'นราธิวาส',
                'Nan' => 'น่าน',
                'Bueng Kan' => 'บึงกาฬ',
                'Buriram' => 'บุรีรัมย์',
                'Pathum Thani' => 'ปทุมธานี',
                'Prachuap Khiri Khan' => 'ประจวบคีรีขันธ์',
                'Prachinburi' => 'ปราจีนบุรี',
                'Pattani' => 'ปัตตานี',
                'Phra Nakhon Si Ayutthaya' => 'พระนครศรีอยุธยา',
                'Phayao' => 'พะเยา',
                'Phang Nga' => 'พังงา',
                'Phatthalung' => 'พัทลุง',
                'Phichit' => 'พิจิตร',
                'Phitsanulok' => 'พิษณุโลก',
                'Phetchaburi' => 'เพชรบุรี',
                'Phetchabun' => 'เพชรบูรณ์',
                'Phrae' => 'แพร่',
                'Phuket' => 'ภูเก็ต',
                'Maha Sarakham' => 'มหาสารคาม',
                'Mukdahan' => 'มุกดาหาร',
                'Mae Hong Son' => 'แม่ฮ่องสอน',
                'Yala' => 'ยะลา',
                'Yasothon' => 'ยโสธร',
                'Ranong' => 'ระนอง',
                'Rayong' => 'ระยอง',
                'Ratchaburi' => 'ราชบุรี',
                'Roi Et' => 'ร้อยเอ็ด',
                'Lopburi' => 'ลพบุรี',
                'Lampang' => 'ลำปาง',
                'Lamphun' => 'ลำพูน',
                'Loei' => 'เลย',
                'Sisaket' => 'ศรีสะเกษ',
                'Sakon Nakhon' => 'สกลนคร',
                'Songkhla' => 'สงขลา',
                'Satun' => 'สตูล',
                'Samut Prakan' => 'สมุทรปราการ',
                'Samut Songkhram' => 'สมุทรสงคราม',
                'Samut Sakhon' => 'สมุทรสาคร',
                'Saraburi' => 'สระบุรี',
                'Sa Kaeo' => 'สระแก้ว',
                'Sing Buri' => 'สิงห์บุรี',
                'Suphan Buri' => 'สุพรรณบุรี',
                'Surat Thani' => 'สุราษฎร์ธานี',
                'Surin' => 'สุรินทร์',
                'Sukhothai Thani' => 'สุโขทัย',
                'Nong Khai' => 'หนองคาย',
                'Nong Bua Lam Phu' => 'หนองบัวลำภู',
                'Amnat Charoen' => 'อำนาจเจริญ',
                'Udon Thani' => 'อุดรธานี',
                'Uttaradit' => 'อุตรดิตถ์',
                'Uthai Thani' => 'อุทัยธานี',
                'Ubon Ratchathani' => 'อุบลราชธานี',
                'Ang Thong' => 'อ่างทอง',
            ],
        ],
        'SG' => [
            'name' => ['th' => 'สิงคโปร์', 'en' => 'Singapore'],
            'phone_cc' => '65',
            'state_key' => 'state_sg',
            'state_label' => ['th' => 'เขต', 'en' => 'Region'],
            'zip_key' => 'zip_sg',
            'zip_pattern' => '/^\\d{6}$/',
            'zip_example' => '018956',
            'regions' => [
                'Central Singapore' => 'Central Singapore',
                'North East' => 'North East',
                'North West' => 'North West',
                'South East' => 'South East',
                'South West' => 'South West',
            ],
        ],
        'MY' => [
            'name' => ['th' => 'มาเลเซีย', 'en' => 'Malaysia'],
            'phone_cc' => '60',
            'state_key' => 'state_my',
            'state_label' => ['th' => 'รัฐ', 'en' => 'State'],
            'zip_key' => 'zip_my',
            'zip_pattern' => '/^\\d{5}$/',
            'zip_example' => '50450',
            'regions' => [
                'Johor' => 'Johor',
                'Kedah' => 'Kedah',
                'Kelantan' => 'Kelantan',
                'Kuala Lumpur' => 'Kuala Lumpur',
                'Labuan' => 'Labuan',
                'Melaka' => 'Melaka',
                'Negeri Sembilan' => 'Negeri Sembilan',
                'Pahang' => 'Pahang',
                'Perak' => 'Perak',
                'Perlis' => 'Perlis',
                'Pulau Pinang' => 'Pulau Pinang',
                'Putrajaya' => 'Putrajaya',
                'Sabah' => 'Sabah',
                'Sarawak' => 'Sarawak',
                'Selangor' => 'Selangor',
                'Terengganu' => 'Terengganu',
            ],
        ],
        'LA' => [
            'name' => ['th' => 'ลาว', 'en' => 'Laos'],
            'phone_cc' => '856',
            'state_key' => 'state_la',
            'state_label' => ['th' => 'แขวง', 'en' => 'Province'],
            'zip_key' => 'zip_la',
            'zip_pattern' => '/^\\d{5}$/',
            'zip_example' => '01000',
            'regions' => [
                'Attapu' => 'Attapu',
                'Bokèo' => 'Bokèo',
                'Bolikhamxai' => 'Bolikhamxai',
                'Champasak' => 'Champasak',
                'Houaphan' => 'Houaphan',
                'Khammouan' => 'Khammouan',
                'Louang Namtha' => 'Louang Namtha',
                'Louangphabang' => 'Louangphabang',
                'Oudômxai' => 'Oudômxai',
                'Phôngsali' => 'Phôngsali',
                'Salavan' => 'Salavan',
                'Savannakhét' => 'Savannakhét',
                'Vientiane' => 'Vientiane',
                'Xaignabouli' => 'Xaignabouli',
                'Xaisomboun' => 'Xaisomboun',
                'Xiangkhouang' => 'Xiangkhouang',
                'Xékong' => 'Xékong',
            ],
        ],
        'KH' => [
            'name' => ['th' => 'กัมพูชา', 'en' => 'Cambodia'],
            'phone_cc' => '855',
            'state_key' => 'state_kh',
            'state_label' => ['th' => 'จังหวัด', 'en' => 'Province'],
            'zip_key' => 'zip_kh',
            'zip_pattern' => '/^\\d{5}$/',
            'zip_example' => '12000',
            'regions' => [
                'Baat Dambang' => 'Baat Dambang',
                'Banteay Mean Chey' => 'Banteay Mean Chey',
                'Kampong Chaam' => 'Kampong Chaam',
                'Kampong Chhnang' => 'Kampong Chhnang',
                'Kampong Spueu' => 'Kampong Spueu',
                'Kampong Thum' => 'Kampong Thum',
                'Kampot' => 'Kampot',
                'Kandaal' => 'Kandaal',
                'Kaoh Kong' => 'Kaoh Kong',
                'Kracheh' => 'Kracheh',
                'Krong Kaeb' => 'Krong Kaeb',
                'Krong Pailin' => 'Krong Pailin',
                'Krong Preah Sihanouk' => 'Krong Preah Sihanouk',
                'Mondol Kiri' => 'Mondol Kiri',
                'Otdar Mean Chey' => 'Otdar Mean Chey',
                'Phnom Penh' => 'Phnom Penh',
                'Pousaat' => 'Pousaat',
                'Preah Vihear' => 'Preah Vihear',
                'Prey Veaeng' => 'Prey Veaeng',
                'Rotanah Kiri' => 'Rotanah Kiri',
                'Siem Reab' => 'Siem Reab',
                'Stueng Treng' => 'Stueng Treng',
                'Svaay Rieng' => 'Svaay Rieng',
                'Taakaev' => 'Taakaev',
                'Tbong Khmum' => 'Tbong Khmum',
            ],
        ],
        'MM' => [
            'name' => ['th' => 'เมียนมา', 'en' => 'Myanmar'],
            'phone_cc' => '95',
            'state_key' => 'state_mm',
            'state_label' => ['th' => 'รัฐ/ภาค', 'en' => 'State / Region'],
            'zip_key' => 'zip_mm',
            'zip_pattern' => '/^\\d{5}$/',
            'zip_example' => '11181',
            'regions' => [
                'Ayeyarwady' => 'Ayeyarwady',
                'Bago' => 'Bago',
                'Chin' => 'Chin',
                'Kachin' => 'Kachin',
                'Kayah' => 'Kayah',
                'Kayin' => 'Kayin',
                'Magway' => 'Magway',
                'Mandalay' => 'Mandalay',
                'Mon' => 'Mon',
                'Nay Pyi Taw' => 'Nay Pyi Taw',
                'Rakhine' => 'Rakhine',
                'Sagaing' => 'Sagaing',
                'Shan' => 'Shan',
                'Tanintharyi' => 'Tanintharyi',
                'Yangon' => 'Yangon',
            ],
        ],
        'VN' => [
            'name' => ['th' => 'เวียดนาม', 'en' => 'Vietnam'],
            'phone_cc' => '84',
            'state_key' => 'state_vn',
            'state_label' => ['th' => 'จังหวัด', 'en' => 'Province'],
            'zip_key' => 'zip_vn',
            'zip_pattern' => '/^\\d{6}$/',
            'zip_example' => '100000',
            'regions' => [
                'Binh Dinh' => 'Bình Định',
                'Can Tho' => 'Cần Thơ',
                'Gia Lai' => 'Gia Lai',
                'Ha Giang' => 'Hà Giang',
                'Ha Nam' => 'Hà Nam',
                'Ha Noi' => 'Hà Nội',
                'Ha Tay' => 'Hà Tây',
                'Ha Tinh' => 'Hà Tĩnh',
                'Hoa Binh' => 'Hòa Bình',
                'Hung Yen' => 'Hưng Yên',
                'Hai Duong' => 'Hải Dương',
                'Hai Phong' => 'Hải Phòng',
                'Hau Giang' => 'Hậu Giang',
                'Ho Chi Minh Sai Gon' => 'Hồ Chí Minh (Sài Gòn)',
                'Khanh Hoa' => 'Khánh Hòa',
                'Kien Giang' => 'Kiên Giang',
                'Kon Tum' => 'Kon Tum',
                'Lai Chau' => 'Lai Châu',
                'Long An' => 'Long An',
                'Lao Cai' => 'Lào Cai',
                'Lam Dong' => 'Lâm Đồng',
                'Lang Son' => 'Lạng Sơn',
                'Nam Dinh' => 'Nam Định',
                'Nghe An' => 'Nghệ An',
                'Ninh Binh' => 'Ninh Bình',
                'Ninh Thuan' => 'Ninh Thuận',
                'Phu Tho' => 'Phú Thọ',
                'Phu Yen' => 'Phú Yên',
                'Quang Binh' => 'Quảng Bình',
                'Quang Nam' => 'Quảng Nam',
                'Quang Ngai' => 'Quảng Ngãi',
                'Quang Ninh' => 'Quảng Ninh',
                'Quang Tri' => 'Quảng Trị',
                'Soc Trang' => 'Sóc Trăng',
                'Son La' => 'Sơn La',
                'Thanh Hoa' => 'Thanh Hóa',
                'Thai Binh' => 'Thái Bình',
                'Thai Nguyen' => 'Thái Nguyên',
                'Thua ThienHue' => 'Thừa Thiên–Huế',
                'Tien Giang' => 'Tiền Giang',
                'Tra Vinh' => 'Trà Vinh',
                'Tuyen Quang' => 'Tuyên Quang',
                'Tay Ninh' => 'Tây Ninh',
                'Vinh Long' => 'Vĩnh Long',
                'Vinh Phuc' => 'Vĩnh Phúc',
                'Yen Bai' => 'Yên Bái',
                'Da Nang' => 'Đà Nẵng',
                'Dong Nai' => 'Đồng Nai',
                'Dong Thap' => 'Đồng Tháp',
            ],
        ],
        'JP' => [
            'name' => ['th' => 'ญี่ปุ่น', 'en' => 'Japan'],
            'phone_cc' => '81',
            'state_key' => 'state_jp',
            'state_label' => ['th' => 'จังหวัด', 'en' => 'Prefecture'],
            'zip_key' => 'zip_jp',
            'zip_pattern' => '/^\\d{3}-\\d{4}$/',
            'zip_example' => '100-0001',
            'regions' => [
                'Aichi' => 'Aichi',
                'Akita' => 'Akita',
                'Aomori' => 'Aomori',
                'Chiba' => 'Chiba',
                'Ehime' => 'Ehime',
                'Fukui' => 'Fukui',
                'Fukuoka' => 'Fukuoka',
                'Fukushima' => 'Fukushima',
                'Gifu' => 'Gifu',
                'Gunma' => 'Gunma',
                'Hiroshima' => 'Hiroshima',
                'Hokkaido' => 'Hokkaido',
                'Hyogo' => 'Hyogo',
                'Ibaraki' => 'Ibaraki',
                'Ishikawa' => 'Ishikawa',
                'Iwate' => 'Iwate',
                'Kagawa' => 'Kagawa',
                'Kagoshima' => 'Kagoshima',
                'Kanagawa' => 'Kanagawa',
                'Kochi' => 'Kochi',
                'Kumamoto' => 'Kumamoto',
                'Kyoto' => 'Kyoto',
                'Mie' => 'Mie',
                'Miyagi' => 'Miyagi',
                'Miyazaki' => 'Miyazaki',
                'Nagano' => 'Nagano',
                'Nagasaki' => 'Nagasaki',
                'Nara' => 'Nara',
                'Niigata' => 'Niigata',
                'Oita' => 'Oita',
                'Okayama' => 'Okayama',
                'Okinawa' => 'Okinawa',
                'Osaka' => 'Osaka',
                'Saga' => 'Saga',
                'Saitama' => 'Saitama',
                'Shiga' => 'Shiga',
                'Shimane' => 'Shimane',
                'Shizuoka' => 'Shizuoka',
                'Tochigi' => 'Tochigi',
                'Tokushima' => 'Tokushima',
                'Tokyo' => 'Tokyo',
                'Tottori' => 'Tottori',
                'Toyama' => 'Toyama',
                'Wakayama' => 'Wakayama',
                'Yamagata' => 'Yamagata',
                'Yamaguchi' => 'Yamaguchi',
                'Yamanashi' => 'Yamanashi',
            ],
        ],
        'KR' => [
            'name' => ['th' => 'เกาหลีใต้', 'en' => 'South Korea'],
            'phone_cc' => '82',
            'state_key' => 'state_kr',
            'state_label' => ['th' => 'จังหวัด', 'en' => 'Province'],
            'zip_key' => 'zip_kr',
            'zip_pattern' => '/^\\d{5}$/',
            'zip_example' => '04524',
            'regions' => [
                'Ch\'ungch\'ongbuk-do' => 'Ch\'ungch\'ongbuk-do',
                'Ch\'ungch\'ongnam-do' => 'Ch\'ungch\'ongnam-do',
                'Cheju-do' => 'Cheju-do',
                'Chollabuk-do' => 'Chollabuk-do',
                'Chollanam-do' => 'Chollanam-do',
                'Inch\'on-Kwangyokhi' => 'Inch\'on-Kwangyokhi',
                'Kang-won-do' => 'Kang-won-do',
                'Kwangju-Kwangyokshi' => 'Kwangju-Kwangyokshi',
                'Kyonggi-do' => 'Kyonggi-do',
                'Kyongsangbuk-do' => 'Kyongsangbuk-do',
                'Kyongsangnam-do' => 'Kyongsangnam-do',
                'Pusan-Kwangyokshi' => 'Pusan-Kwangyokshi',
                'Sejong' => 'Sejong',
                'Seoul-T\'ukpyolshi' => 'Seoul-T\'ukpyolshi',
                'Taegu-Kwangyokshi' => 'Taegu-Kwangyokshi',
                'Taejon-Kwangyokshi' => 'Taejon-Kwangyokshi',
                'Ulsan-Kwangyokshi' => 'Ulsan-Kwangyokshi',
            ],
        ],
        'CN' => [
            'name' => ['th' => 'จีน', 'en' => 'China'],
            'phone_cc' => '86',
            'state_key' => 'state_cn',
            'state_label' => ['th' => 'มณฑล', 'en' => 'Province'],
            'zip_key' => 'zip_cn',
            'zip_pattern' => '/^\\d{6}$/',
            'zip_example' => '100000',
            'regions' => [
                'Anhui' => 'Anhui',
                'Beijing' => 'Beijing',
                'Chongqing' => 'Chongqing',
                'Fujian' => 'Fujian',
                'Gansu' => 'Gansu',
                'Guangdong' => 'Guangdong',
                'Guangxi' => 'Guangxi',
                'Guizhou' => 'Guizhou',
                'Hainan' => 'Hainan',
                'Hebei' => 'Hebei',
                'Heilongjiang' => 'Heilongjiang',
                'Henan' => 'Henan',
                'Hong Kong' => 'Hong Kong',
                'Hubei' => 'Hubei',
                'Hunan' => 'Hunan',
                'Inner Mongolia' => 'Inner Mongolia',
                'Jiangsu' => 'Jiangsu',
                'Jiangxi' => 'Jiangxi',
                'Jilin' => 'Jilin',
                'Liaoning' => 'Liaoning',
                'Macau' => 'Macau',
                'Ningxia' => 'Ningxia',
                'Qinghai' => 'Qinghai',
                'Shaanxi' => 'Shaanxi',
                'Shandong' => 'Shandong',
                'Shanghai' => 'Shanghai',
                'Shanxi' => 'Shanxi',
                'Sichuan' => 'Sichuan',
                'Tianjin' => 'Tianjin',
                'Tibet' => 'Tibet',
                'Xinjiang' => 'Xinjiang',
                'Yunnan' => 'Yunnan',
                'Zhejiang' => 'Zhejiang',
            ],
        ],
        'TW' => [
            'name' => ['th' => 'ไต้หวัน', 'en' => 'Taiwan'],
            'phone_cc' => '886',
            'state_key' => 'state_tw',
            'state_label' => ['th' => 'เขต', 'en' => 'County / City'],
            'zip_key' => 'zip_tw',
            'zip_pattern' => '/^\\d{5}$/',
            'zip_example' => '10001',
            'regions' => [
                'Chang-hua' => 'Chang-hua',
                'Chia-i' => 'Chia-i',
                'Hsin-chu' => 'Hsin-chu',
                'Hua-lien' => 'Hua-lien',
                'Kao-hsiung' => 'Kao-hsiung',
                'Keelung' => 'Keelung',
                'Kinmen' => 'Kinmen',
                'Lienchiang' => 'Lienchiang',
                'Miao-li' => 'Miao-li',
                'Nan-t\'ou' => 'Nan-t\'ou',
                'New Taipei' => 'New Taipei',
                'P\'eng-hu' => 'P\'eng-hu',
                'P\'ing-chung' => 'P\'ing-chung',
                'T\'ai-chung' => 'T\'ai-chung',
                'T\'ai-nan' => 'T\'ai-nan',
                'T\'ai-pei' => 'T\'ai-pei',
                'T\'ai-tung' => 'T\'ai-tung',
                'T\'ao-yuan' => 'T\'ao-yuan',
                'Yi-lan' => 'Yi-lan',
                'Yun-lin' => 'Yun-lin',
            ],
        ],
        'HK' => [
            'name' => ['th' => 'ฮ่องกง', 'en' => 'Hong Kong'],
            'phone_cc' => '852',
            'state_key' => 'state_hk',
            'state_label' => ['th' => 'เขต', 'en' => 'Region'],
            'zip_key' => 'zip_general',
            'zip_pattern' => '/^[A-Z0-9]{2,10}$/',
            'zip_example' => '000000',
            'regions' => [
                'Hong Kong' => 'Hong Kong',
            ],
        ],
        'AU' => [
            'name' => ['th' => 'ออสเตรเลีย', 'en' => 'Australia'],
            'phone_cc' => '61',
            'state_key' => 'state_au',
            'state_label' => ['th' => 'รัฐ', 'en' => 'State'],
            'zip_key' => 'zip_au',
            'zip_pattern' => '/^\\d{4}$/',
            'zip_example' => '2000',
            'regions' => [
                'Australian Capital Territory' => 'Australian Capital Territory',
                'New South Wales' => 'New South Wales',
                'Northern Territory' => 'Northern Territory',
                'Queensland' => 'Queensland',
                'South Australia' => 'South Australia',
                'Tasmania' => 'Tasmania',
                'Victoria' => 'Victoria',
                'Western Australia' => 'Western Australia',
            ],
        ],
        'GB' => [
            'name' => ['th' => 'สหราชอาณาจักร', 'en' => 'United Kingdom'],
            'phone_cc' => '44',
            'state_key' => 'state_gb',
            'state_label' => ['th' => 'เขต', 'en' => 'County'],
            'zip_key' => 'zip_gb',
            'zip_pattern' => '/^[A-Z]{1,2}\\d[A-Z\\d]? \\d[A-Z]{2}$/',
            'zip_example' => 'SW1A 1AA',
            'regions' => [
                'Aberdeen City' => 'Aberdeen City',
                'Aberdeenshire' => 'Aberdeenshire',
                'Angus' => 'Angus',
                'Antrim and Newtownabbey' => 'Antrim and Newtownabbey',
                'Ards and North Down' => 'Ards and North Down',
                'Argyll and Bute' => 'Argyll and Bute',
                'Armagh, Banbridge and Craigavon' => 'Armagh, Banbridge and Craigavon',
                'Barking and Dagenham' => 'Barking and Dagenham',
                'Barnet' => 'Barnet',
                'Barnsley' => 'Barnsley',
                'Bath and North East Somerset' => 'Bath and North East Somerset',
                'Bedford' => 'Bedford',
                'Belfast' => 'Belfast',
                'Bexley' => 'Bexley',
                'Birmingham' => 'Birmingham',
                'Blackburn with Darwen' => 'Blackburn with Darwen',
                'Blackpool' => 'Blackpool',
                'Blaenau Gwent' => 'Blaenau Gwent',
                'Bolton' => 'Bolton',
                'Bournemouth' => 'Bournemouth',
                'Bracknell Forest' => 'Bracknell Forest',
                'Bradford' => 'Bradford',
                'Brent' => 'Brent',
                'Bridgend' => 'Bridgend',
                'Brighton and Hove' => 'Brighton and Hove',
                'Bristol' => 'Bristol',
                'Bromley' => 'Bromley',
                'Buckinghamshire' => 'Buckinghamshire',
                'Bury' => 'Bury',
                'Caerphilly' => 'Caerphilly',
                'Calderdale' => 'Calderdale',
                'Cambridgeshire' => 'Cambridgeshire',
                'Camden' => 'Camden',
                'Cardiff' => 'Cardiff',
                'Carmarthenshire' => 'Carmarthenshire',
                'Causeway Coast and Glens' => 'Causeway Coast and Glens',
                'Central Bedfordshire' => 'Central Bedfordshire',
                'Ceredigion' => 'Ceredigion',
                'Cheshire East' => 'Cheshire East',
                'Cheshire West and Chester' => 'Cheshire West and Chester',
                'Clackmannanshire' => 'Clackmannanshire',
                'Conwy' => 'Conwy',
                'Cornwall' => 'Cornwall',
                'Coventry' => 'Coventry',
                'Croydon' => 'Croydon',
                'Cumbria' => 'Cumbria',
                'Darlington' => 'Darlington',
                'Denbighshire' => 'Denbighshire',
                'Derby' => 'Derby',
                'Derbyshire' => 'Derbyshire',
                'Derry and Strabane' => 'Derry and Strabane',
                'Devon' => 'Devon',
                'Doncaster' => 'Doncaster',
                'Dorset' => 'Dorset',
                'Dudley' => 'Dudley',
                'Dumfries and Galloway' => 'Dumfries and Galloway',
                'Dundee City' => 'Dundee City',
                'Durham County' => 'Durham County',
                'Ealing' => 'Ealing',
                'East Ayrshire' => 'East Ayrshire',
                'East Dunbartonshire' => 'East Dunbartonshire',
                'East Lothian' => 'East Lothian',
                'East Renfrewshire' => 'East Renfrewshire',
                'East Riding of Yorkshire' => 'East Riding of Yorkshire',
                'East Sussex' => 'East Sussex',
                'Edinburgh' => 'Edinburgh',
                'Eilean Siar' => 'Eilean Siar',
                'Enfield' => 'Enfield',
                'Essex' => 'Essex',
                'Falkirk' => 'Falkirk',
                'Fermanagh and Omagh' => 'Fermanagh and Omagh',
                'Fife' => 'Fife',
                'Flintshire' => 'Flintshire',
                'Gateshead' => 'Gateshead',
                'Glasgow City' => 'Glasgow City',
                'Gloucestershire' => 'Gloucestershire',
                'London' => 'Greater London',
                'Greenwich' => 'Greenwich',
                'Gwynedd' => 'Gwynedd',
                'Hackney' => 'Hackney',
                'Halton' => 'Halton',
                'Hammersmith and Fulham' => 'Hammersmith and Fulham',
                'Hampshire' => 'Hampshire',
                'Haringey' => 'Haringey',
                'Harrow' => 'Harrow',
                'Hartlepool' => 'Hartlepool',
                'Havering' => 'Havering',
                'Herefordshire' => 'Herefordshire',
                'Hertfordshire' => 'Hertfordshire',
                'Highland' => 'Highland',
                'Hillingdon' => 'Hillingdon',
                'Hounslow' => 'Hounslow',
                'Inverclyde' => 'Inverclyde',
                'Isle of Anglesey' => 'Isle of Anglesey',
                'Isle of Wight' => 'Isle of Wight',
                'Isles of Scilly' => 'Isles of Scilly',
                'Islington' => 'Islington',
                'Kensington and Chelsea' => 'Kensington and Chelsea',
                'Kent' => 'Kent',
                'Kingston upon Hull' => 'Kingston upon Hull',
                'Kingston upon Thames' => 'Kingston upon Thames',
                'Kirklees' => 'Kirklees',
                'Knowsley' => 'Knowsley',
                'Lambeth' => 'Lambeth',
                'Lancashire' => 'Lancashire',
                'Leeds' => 'Leeds',
                'Leicester' => 'Leicester',
                'Leicestershire' => 'Leicestershire',
                'Lewisham' => 'Lewisham',
                'Lincolnshire' => 'Lincolnshire',
                'Lisburn and Castlereagh' => 'Lisburn and Castlereagh',
                'Liverpool' => 'Liverpool',
                'Luton' => 'Luton',
                'Manchester' => 'Manchester',
                'Medway' => 'Medway',
                'Merthyr Tydfil' => 'Merthyr Tydfil',
                'Merton' => 'Merton',
                'Mid and East Antrim' => 'Mid and East Antrim',
                'Mid Ulster' => 'Mid Ulster',
                'Middlesbrough' => 'Middlesbrough',
                'Midlothian' => 'Midlothian',
                'Milton Keynes' => 'Milton Keynes',
                'Monmouthshire' => 'Monmouthshire',
                'Moray' => 'Moray',
                'Neath Port Talbot' => 'Neath Port Talbot',
                'Newcastle upon Tyne' => 'Newcastle upon Tyne',
                'Newham' => 'Newham',
                'Newport' => 'Newport',
                'Newry, Mourne and Down' => 'Newry, Mourne and Down',
                'Norfolk' => 'Norfolk',
                'North Ayrshire' => 'North Ayrshire',
                'North East Lincolnshire' => 'North East Lincolnshire',
                'North Lanarkshire' => 'North Lanarkshire',
                'North Lincolnshire' => 'North Lincolnshire',
                'North Somerset' => 'North Somerset',
                'North Tyneside' => 'North Tyneside',
                'North Yorkshire' => 'North Yorkshire',
                'Northamptonshire' => 'Northamptonshire',
                'Northumberland' => 'Northumberland',
                'Nottingham' => 'Nottingham',
                'Nottinghamshire' => 'Nottinghamshire',
                'Oldham' => 'Oldham',
                'Orkney Islands' => 'Orkney Islands',
                'Oxfordshire' => 'Oxfordshire',
                'Pembrokeshire' => 'Pembrokeshire',
                'Perth and Kinross' => 'Perth and Kinross',
                'Peterborough' => 'Peterborough',
                'Plymouth' => 'Plymouth',
                'Poole' => 'Poole',
                'Portsmouth' => 'Portsmouth',
                'Powys' => 'Powys',
                'Reading' => 'Reading',
                'Redbridge' => 'Redbridge',
                'Redcar and Cleveland' => 'Redcar and Cleveland',
                'Renfrewshire' => 'Renfrewshire',
                'Rhondda, Cynon, Taff' => 'Rhondda, Cynon, Taff',
                'Richmond upon Thames' => 'Richmond upon Thames',
                'Rochdale' => 'Rochdale',
                'Rotherham' => 'Rotherham',
                'Rutland' => 'Rutland',
                'Salford' => 'Salford',
                'Sandwell' => 'Sandwell',
                'Scottish Borders, The' => 'Scottish Borders, The',
                'Sefton' => 'Sefton',
                'Sheffield' => 'Sheffield',
                'Shetland Islands' => 'Shetland Islands',
                'Shropshire' => 'Shropshire',
                'Slough' => 'Slough',
                'Solihull' => 'Solihull',
                'Somerset' => 'Somerset',
                'South Ayrshire' => 'South Ayrshire',
                'South Gloucestershire' => 'South Gloucestershire',
                'South Lanarkshire' => 'South Lanarkshire',
                'South Tyneside' => 'South Tyneside',
                'Southampton' => 'Southampton',
                'Southend-on-Sea' => 'Southend-on-Sea',
                'Southwark' => 'Southwark',
                'St. Helens' => 'St. Helens',
                'Staffordshire' => 'Staffordshire',
                'Stirling' => 'Stirling',
                'Stockport' => 'Stockport',
                'Stockton-on-Tees' => 'Stockton-on-Tees',
                'Stoke-on-Trent' => 'Stoke-on-Trent',
                'Suffolk' => 'Suffolk',
                'Sunderland' => 'Sunderland',
                'Surrey' => 'Surrey',
                'Sutton' => 'Sutton',
                'Swansea' => 'Swansea',
                'Swindon' => 'Swindon',
                'Tameside' => 'Tameside',
                'Telford and Wrekin' => 'Telford and Wrekin',
                'Thurrock' => 'Thurrock',
                'Torbay' => 'Torbay',
                'Torfaen' => 'Torfaen',
                'Tower Hamlets' => 'Tower Hamlets',
                'Trafford' => 'Trafford',
                'Vale of Glamorgan, The' => 'Vale of Glamorgan, The',
                'Wakefield' => 'Wakefield',
                'Walsall' => 'Walsall',
                'Waltham Forest' => 'Waltham Forest',
                'Wandsworth' => 'Wandsworth',
                'Warrington' => 'Warrington',
                'Warwickshire' => 'Warwickshire',
                'West Berkshire' => 'West Berkshire',
                'West Dunbartonshire' => 'West Dunbartonshire',
                'West Lothian' => 'West Lothian',
                'West Sussex' => 'West Sussex',
                'West Yorkshire' => 'West Yorkshire',
                'Westminster' => 'Westminster',
                'Wigan' => 'Wigan',
                'Wiltshire' => 'Wiltshire',
                'Windsor and Maidenhead' => 'Windsor and Maidenhead',
                'Wirral' => 'Wirral',
                'Wokingham' => 'Wokingham',
                'Wolverhampton' => 'Wolverhampton',
                'Worcestershire' => 'Worcestershire',
                'Wrexham' => 'Wrexham',
                'York' => 'York',
            ],
        ],
        'US' => [
            'name' => ['th' => 'สหรัฐอเมริกา', 'en' => 'United States'],
            'phone_cc' => '1',
            'state_key' => 'state_us',
            'state_label' => ['th' => 'รัฐ', 'en' => 'State'],
            'zip_key' => 'zip_us',
            'zip_pattern' => '/^\\d{5}(-\\d{4})?$/',
            'zip_example' => '10001',
            'regions' => [
                'AL' => 'Alabama',
                'AK' => 'Alaska',
                'AS' => 'American Samoa',
                'AZ' => 'Arizona',
                'AR' => 'Arkansas',
                'AA' => 'Armed Forces (AA)',
                'AE' => 'Armed Forces (AE)',
                'AP' => 'Armed Forces (AP)',
                'CA' => 'California',
                'CO' => 'Colorado',
                'CT' => 'Connecticut',
                'DE' => 'Delaware',
                'DC' => 'District Of Columbia',
                'FL' => 'Florida',
                'GA' => 'Georgia',
                'GU' => 'Guam',
                'HI' => 'Hawaii',
                'ID' => 'Idaho',
                'IL' => 'Illinois',
                'IN' => 'Indiana',
                'IA' => 'Iowa',
                'KS' => 'Kansas',
                'KY' => 'Kentucky',
                'LA' => 'Louisiana',
                'ME' => 'Maine',
                'MH' => 'Marshall Islands',
                'MD' => 'Maryland',
                'MA' => 'Massachusetts',
                'MI' => 'Michigan',
                'FM' => 'Micronesia',
                'MN' => 'Minnesota',
                'MS' => 'Mississippi',
                'MO' => 'Missouri',
                'MT' => 'Montana',
                'NE' => 'Nebraska',
                'NV' => 'Nevada',
                'NH' => 'New Hampshire',
                'NJ' => 'New Jersey',
                'NM' => 'New Mexico',
                'NY' => 'New York',
                'NC' => 'North Carolina',
                'ND' => 'North Dakota',
                'MP' => 'Northern Mariana Islands',
                'OH' => 'Ohio',
                'OK' => 'Oklahoma',
                'OR' => 'Oregon',
                'PW' => 'Palau',
                'PA' => 'Pennsylvania',
                'PR' => 'Puerto Rico',
                'RI' => 'Rhode Island',
                'SC' => 'South Carolina',
                'SD' => 'South Dakota',
                'TN' => 'Tennessee',
                'TX' => 'Texas',
                'UT' => 'Utah',
                'VT' => 'Vermont',
                'VI' => 'Virgin Islands',
                'VA' => 'Virginia',
                'WA' => 'Washington',
                'WV' => 'West Virginia',
                'WI' => 'Wisconsin',
                'WY' => 'Wyoming',
            ],
        ],
        'DE' => [
            'name' => ['th' => 'เยอรมนี', 'en' => 'Germany'],
            'phone_cc' => '49',
            'state_key' => 'state_de',
            'state_label' => ['th' => 'รัฐ', 'en' => 'State'],
            'zip_key' => 'zip_de',
            'zip_pattern' => '/^\\d{5}$/',
            'zip_example' => '10115',
            'regions' => [
                'Baden-Württemberg' => 'Baden-Württemberg',
                'Bayern' => 'Bayern',
                'Berlin' => 'Berlin',
                'Brandenburg' => 'Brandenburg',
                'Bremen' => 'Bremen',
                'Hamburg' => 'Hamburg',
                'Hessen' => 'Hessen',
                'Mecklenburg-Vorpommern' => 'Mecklenburg-Vorpommern',
                'Niedersachsen' => 'Niedersachsen',
                'Nordrhein-Westfalen' => 'Nordrhein-Westfalen',
                'Rheinland-Pfalz' => 'Rheinland-Pfalz',
                'Saarland' => 'Saarland',
                'Sachsen' => 'Sachsen',
                'Sachsen-Anhalt' => 'Sachsen-Anhalt',
                'Schleswig-Holstein' => 'Schleswig-Holstein',
                'Thüringen' => 'Thüringen',
            ],
        ],
        'FR' => [
            'name' => ['th' => 'ฝรั่งเศส', 'en' => 'France'],
            'phone_cc' => '33',
            'state_key' => 'state_fr',
            'state_label' => ['th' => 'แคว้น', 'en' => 'Region'],
            'zip_key' => 'zip_fr',
            'zip_pattern' => '/^\\d{5}$/',
            'zip_example' => '75001',
            'regions' => [
                'Auvergne-Rhône-Alpes' => 'Auvergne-Rhône-Alpes',
                'Bourgogne-Franche-Comté' => 'Bourgogne-Franche-Comté',
                'Bretagne' => 'Bretagne',
                'Centre-Val de Loire' => 'Centre-Val de Loire',
                'Clipperton' => 'Clipperton',
                'Corse' => 'Corse',
                'Grand Est' => 'Grand Est',
                'Guadeloupe' => 'Guadeloupe',
                'Guyane' => 'Guyane',
                'Hauts-de-France' => 'Hauts-de-France',
                'Martinique' => 'Martinique',
                'Mayotte' => 'Mayotte',
                'Normandie' => 'Normandie',
                'Nouvelle-Aquitaine' => 'Nouvelle-Aquitaine',
                'Novelle-Calédonie' => 'Novelle-Calédonie',
                'Occitanie' => 'Occitanie',
                'Pays de la Loire' => 'Pays de la Loire',
                'Polynésie' => 'Polynésie',
                'Provence-Alpes-Cote dAzur' => 'Provence-Alpes-Cote dAzur',
                'Réunion' => 'Réunion',
                'Saint Barthélemy' => 'Saint Barthélemy',
                'Saint Martin' => 'Saint Martin',
                'Saint-Pierre-et-Miquelon' => 'Saint-Pierre-et-Miquelon',
                'Terres Australes Françaises' => 'Terres Australes Françaises',
                'Wallis-et-Futuna' => 'Wallis-et-Futuna',
                'Île-de-France' => 'Île-de-France',
            ],
        ],
    ],

    /*
    | Thai postcodes: the first two digits name the province, except a handful
    | of 10xxx codes that belong to Samut Prakan rather than Bangkok. Used to
    | pick the province for the customer, never to refuse an order.
    */
    'th_postcode_prefixes' => [
        '10' => 'Bangkok',
        '11' => 'Nonthaburi',
        '12' => 'Pathum Thani',
        '13' => 'Phra Nakhon Si Ayutthaya',
        '14' => 'Ang Thong',
        '15' => 'Lopburi',
        '16' => 'Sing Buri',
        '17' => 'Chai Nat',
        '18' => 'Saraburi',
        '20' => 'Chonburi',
        '21' => 'Rayong',
        '22' => 'Chanthaburi',
        '23' => 'Trat',
        '24' => 'Chachoengsao',
        '25' => 'Prachinburi',
        '26' => 'Nakhon Nayok',
        '27' => 'Sa Kaeo',
        '30' => 'Nakhon Ratchasima',
        '31' => 'Buriram',
        '32' => 'Surin',
        '33' => 'Sisaket',
        '34' => 'Ubon Ratchathani',
        '35' => 'Yasothon',
        '36' => 'Chaiyaphum',
        '37' => 'Amnat Charoen',
        '38' => 'Bueng Kan',
        '39' => 'Nong Bua Lam Phu',
        '40' => 'Khon Kaen',
        '41' => 'Udon Thani',
        '42' => 'Loei',
        '43' => 'Nong Khai',
        '44' => 'Maha Sarakham',
        '45' => 'Roi Et',
        '46' => 'Kalasin',
        '47' => 'Sakon Nakhon',
        '48' => 'Nakhon Phanom',
        '49' => 'Mukdahan',
        '50' => 'Chiang Mai',
        '51' => 'Lamphun',
        '52' => 'Lampang',
        '53' => 'Uttaradit',
        '54' => 'Phrae',
        '55' => 'Nan',
        '56' => 'Phayao',
        '57' => 'Chiang Rai',
        '58' => 'Mae Hong Son',
        '60' => 'Nakhon Sawan',
        '61' => 'Uthai Thani',
        '62' => 'Kamphaeng Phet',
        '63' => 'Tak',
        '64' => 'Sukhothai Thani',
        '65' => 'Phitsanulok',
        '66' => 'Phichit',
        '67' => 'Phetchabun',
        '70' => 'Ratchaburi',
        '71' => 'Kanchanaburi',
        '72' => 'Suphan Buri',
        '73' => 'Nakhon Pathom',
        '74' => 'Samut Sakhon',
        '75' => 'Samut Songkhram',
        '76' => 'Phetchaburi',
        '77' => 'Prachuap Khiri Khan',
        '80' => 'Nakhon Si Thammarat',
        '81' => 'Krabi',
        '82' => 'Phang Nga',
        '83' => 'Phuket',
        '84' => 'Surat Thani',
        '85' => 'Ranong',
        '86' => 'Chumphon',
        '90' => 'Songkhla',
        '91' => 'Satun',
        '92' => 'Trang',
        '93' => 'Phatthalung',
        '94' => 'Pattani',
        '95' => 'Yala',
        '96' => 'Narathiwat',
    ],

    'th_postcode_exceptions' => [
        '10130' => 'Samut Prakan',
        '10270' => 'Samut Prakan',
        '10280' => 'Samut Prakan',
        '10290' => 'Samut Prakan',
        '10540' => 'Samut Prakan',
        '10560' => 'Samut Prakan',
        '10570' => 'Samut Prakan',
    ],
];
