@extends($adminLayout ?? 'layouts.admin')
@section('title', 'เกม: ตรวจสลิป รางวัล และชุมชน')
@section('page-title', 'ศูนย์สนับสนุนเกม')
@section('content')
<link rel="stylesheet" href="{{ asset('css/game-support.css') }}">
<div class="gs-wrap" style="color:#e5edf3;background:#08111b;border-radius:12px">
<h1>ตรวจสลิปและดูแลชุมชนเกม</h1><p><a href="{{ route('game-support.index') }}" target="_blank" rel="noopener">เปิดหน้าอันดับสาธารณะ ↗</a></p>
@if(session('success'))<p class="gs-success" role="status">{{ session('success') }}</p>@endif
@if($errors->any())<div class="gs-error" role="alert">@foreach($errors->all() as $e)<p>{{ $e }}</p>@endforeach</div>@endif
<p>บัญชีกลาง: {{ config('game-support.bank.name') }} · {{ config('game-support.bank.account') }} · {{ config('game-support.bank.holder') }}</p>
<p class="gs-muted">ตรวจด้วยเจ้าหน้าที่: ตรวจผู้รับ ยอด เวลา และเงินเข้าจากธนาคารก่อนอนุมัติ ระบบป้องกันไฟล์ซ้ำและเลขอ้างอิงซ้ำ แต่ไม่ได้รับรองความแท้ของภาพสลิปอัตโนมัติ</p>
<nav class="gs-presets">@foreach(['pending'=>'รอตรวจ','approved'=>'ยืนยันแล้ว','rejected'=>'ไม่ผ่าน','void'=>'ยกเลิกยอด'] as $key=>$label)<a class="gs-small" href="{{ route('admin.game-support.index', ['status'=>$key]) }}">{{ $label }}</a>@endforeach</nav>
<h2>รายการ: {{ $status }}</h2>
@forelse($donations as $d)<article class="gs-admin-row"><h3>{{ $d->campaign->name }} · ฿{{ number_format($d->amount_satang / 100, 2) }} · {{ $d->display_name }}</h3><p>รายการ {{ $d->public_id }} · สมาชิก #{{ $d->user_id }} · {{ $d->created_at }} · {{ $d->publish_name ? 'ยินยอมแสดงชื่อ' : 'ไม่เปิดเผยชื่อ' }}</p><p>ผู้รับที่บันทึกตอนส่ง: {{ $d->bank_snapshot['name'] }} {{ $d->bank_snapshot['account'] }} {{ $d->bank_snapshot['holder'] }}</p><p class="gs-comment">คำแนะนำ: {{ $d->comment ?: '—' }}</p><a href="{{ route('admin.game-support.slip', $d) }}" target="_blank" rel="noopener">เปิดสลิปส่วนตัว ↗</a><p>รางวัล: {{ $d->reward_snapshot['name'] }} / {{ implode(' · ', $d->reward_snapshot['rewards']) }} · {{ $d->reward_status }}</p>
@if($d->status === 'pending')<form action="{{ route('admin.game-support.review', $d) }}" method="post" class="gs-form">@csrf<label>ผลตรวจ<select name="decision" required><option value="rejected">ไม่ผ่าน / ข้อมูลไม่ครบ</option><option value="approved">อนุมัติยอด</option></select></label><label>ยอดที่ตรวจจากธนาคาร (จำเป็นเมื่ออนุมัติ)<input name="verified_amount" inputmode="decimal" placeholder="กรอกยอดที่ตรวจได้จริง"></label><label>เลขอ้างอิงธุรกรรมจากธนาคาร<input name="bank_reference" maxlength="120" placeholder="ตัวอักษร ตัวเลข หรือขีด 6–120 ตัว"></label><label class="gs-check"><input type="checkbox" name="recipient_checked" value="1">ตรวจผู้รับตรงกับบัญชีบริษัทแล้ว</label><label class="gs-check"><input type="checkbox" name="money_received" value="1">ตรวจเงินเข้าจากธนาคารแล้ว (ไม่ใช่อาศัยภาพสลิปอย่างเดียว)</label><label>ข้อความแจ้งผู้บริจาค / เหตุผล<textarea name="review_note" maxlength="2000" required></textarea></label><button type="submit" class="gs-button">บันทึกผลตรวจ</button></form>
@elseif($d->status === 'approved')
@if($d->reward_status === 'available')<form method="post" action="{{ route('admin.game-support.reward', $d) }}" class="gs-form">@csrf<label>บันทึกการส่งมอบรางวัล<input name="note" required maxlength="1000" placeholder="ระบุรางวัลและวิธีส่งมอบ"></label><button class="gs-small">บันทึกว่าส่งมอบแล้ว</button></form>@endif
<details><summary>ยกเลิกการนับยอดกรณีตรวจผิดหรือคืนเงินแล้ว</summary><form method="post" action="{{ route('admin.game-support.void', $d) }}" class="gs-form">@csrf<label>เหตุผลที่จำเป็นต่อการตรวจย้อนหลัง<input name="note" required maxlength="1000"></label><button class="gs-small gs-danger">ยกเลิกยอดและสิทธิ์รางวัล</button><small>ระบบนี้ไม่โอนเงินคืนให้อัตโนมัติ</small></form></details>
@endif
<details><summary>ประวัติการตรวจ</summary>@foreach($d->audit ?? [] as $event)<p>{{ $event['at'] }} · {{ $event['action'] }} · ผู้ดูแล #{{ $event['by'] }} · {{ $event['note'] }}</p>@endforeach</details></article>@empty<p>ไม่มีรายการในสถานะนี้</p>@endforelse{{ $donations->links() }}
<h2>ดูแลความคิดเห็น</h2><nav class="gs-presets">@foreach(['pending'=>'รอตรวจ','approved'=>'เผยแพร่แล้ว','rejected'=>'ซ่อนไว้'] as $key=>$label)<a class="gs-small" href="{{ route('admin.game-support.index', ['status'=>$status, 'comment_status'=>$key]) }}">{{ $label }}</a>@endforeach</nav><p class="gs-muted">สถานะ: {{ $commentStatus }} · เปลี่ยนผลตรวจเพื่อซ่อนข้อความที่เคยเผยแพร่ได้</p>@forelse($comments as $c)<article class="gs-admin-row"><b>{{ $c->display_name }} · {{ $c->campaign->name }}</b><p class="gs-comment">{{ $c->body }}</p><form method="post" action="{{ route('admin.game-support.moderate', $c) }}">@csrf<button class="gs-small" name="status" value="approved">เผยแพร่</button> <button class="gs-small gs-danger" name="status" value="rejected">ไม่เผยแพร่</button></form></article>@empty<p>ไม่มีข้อความในสถานะนี้</p>@endforelse{{ $comments->links() }}
<details class="gs-admin-row"><summary>ยอดสนับสนุน โหวต และดาวแยกตามเกม</summary><div class="gs-grid gs-three">@foreach($stats as $g)<div class="gs-reward"><b>{{ $g['name'] }}</b><p>฿{{ number_format($g['raised'], 2) }} · {{ $g['supporters'] }} ผู้สนับสนุน</p><p>{{ $g['votes'] }} โหวต · {{ $g['rating_count'] ? number_format($g['stars'], 2).' ★ ('.$g['rating_count'].' คะแนน)' : 'ยังไม่มีดาว' }}</p></div>@endforeach</div></details><h2>จัดการโครงการและรางวัล</h2><p class="gs-muted">เปลี่ยนรางวัลมีผลเฉพาะรายการใหม่ รายการเดิมเก็บเงื่อนไขเดิมไว้ เป้าทุน 0 หมายถึงยังไม่ประกาศเป้า</p>
@foreach($campaigns->concat([null]) as $campaign)<details class="gs-admin-row"><summary>{{ $campaign?->name ?? '+ เพิ่มเกมใหม่' }}</summary><form method="post" action="{{ $campaign ? route('admin.game-support.campaign.update', $campaign) : route('admin.game-support.campaign.create') }}" class="gs-form">@csrf<label>รหัสเกม (slug)<input name="slug" value="{{ $campaign?->slug }}" @readonly($campaign) required></label><label>ชื่อเกม<input name="name" value="{{ $campaign?->name }}" required></label><label>คำอธิบาย<textarea name="description">{{ $campaign?->description }}</textarea></label><label>เป้าทุน (บาท)<input name="goal" type="number" min="0" max="100000000" value="{{ ($campaign?->goal_satang ?? 0) / 100 }}" required></label><label class="gs-check"><input type="checkbox" name="active" value="1" @checked($campaign?->active ?? true)>เปิดรับรายการและแสดงในอันดับ</label><label>ระดับรางวัล (JSON: minimum, name, rewards)<textarea name="tiers_json" rows="9" required>{{ json_encode($campaign?->tiers ?? config('game-support.tiers'), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) }}</textarea></label><button class="gs-button">บันทึกโครงการ</button></form></details>@endforeach
</div>
@endsection
