@extends('game-support.layout')
@section('title', $campaign->name)
@section('content')
<a href="{{ route('game-support.index') }}">← อันดับและเกมทั้งหมด</a><div class="gs-hero"><span class="gs-tag">SUPPORT THE NEXT MISSION</span><h1>{{ $campaign->name }}</h1><p>{{ $campaign->description }}</p><div class="gs-metrics"><strong>฿{{ number_format($stats['raised'], 2) }}</strong><span>@if($stats['goal'])จากเป้า ฿{{ number_format($stats['goal']) }}@elseยังไม่กำหนดเป้าทุน@endif · {{ $stats['supporters'] }} ผู้สนับสนุน</span></div>@if($stats['goal'])<progress max="{{ $stats['goal'] }}" value="{{ min($stats['raised'], $stats['goal']) }}" aria-label="ยอดสนับสนุนที่ตรวจแล้ว"></progress>@endif</div>
<div class="gs-grid"><section class="gs-card" id="donate"><h2>ร่วมสนับสนุนเกมนี้</h2><div class="gs-bank"><img src="{{ asset('images/banks/scb.svg') }}" alt="ธนาคารไทยพาณิชย์" width="150" height="45"><div><b>{{ $bank['name'] }}</b><p>{{ $bank['holder'] }}</p><strong class="gs-account">{{ $bank['account'] }}</strong><button type="button" data-copy="4111484769" class="gs-small">คัดลอกเลขบัญชี</button><span data-copy-status role="status"></span></div></div><p class="gs-muted">ใช้บัญชีบริษัทเดียวกันทุกเกม เลือกยอด โอนผ่านแอปธนาคาร แล้วแนบสลิปที่นี่ ตรวจชื่อผู้รับก่อนโอน เลขนี้เป็นบัญชีธนาคาร ไม่ใช่หมายเลขพร้อมเพย์</p>
@auth
<form method="post" enctype="multipart/form-data" action="{{ route('game-support.donate', $campaign) }}" class="gs-form">@csrf
<label>ยอดที่โอน (บาท)<input id="donation-amount" name="amount" inputmode="decimal" pattern="[0-9]+(\.[0-9]{1,2})?" value="{{ old('amount', is_scalar(request('amount')) ? request('amount', '300') : '300') }}" required></label>
<div class="gs-presets">@foreach($campaign->tiers as $tier)<button type="button" data-amount="{{ $tier['minimum'] }}">฿{{ number_format($tier['minimum']) }}</button>@endforeach</div>
<label>ชื่อสำหรับรายการ / ชื่อที่อยากแสดง<input name="display_name" maxlength="80" value="{{ old('display_name', auth()->user()->name) }}" required></label>
<label class="gs-check"><input type="checkbox" name="publish_name" value="1" @checked(old('publish_name'))> ยินยอมแสดงชื่อนี้ ยอด และรางวัลบนหน้าผู้สนับสนุน</label>
<label>สลิปการโอน (JPG / PNG / WebP ไม่เกิน 5 MB)<input type="file" name="slip" accept="image/jpeg,image/png,image/webp" required></label>
<label>คำแนะนำถึงทีม (ไม่บังคับ)<textarea name="comment" maxlength="2000" rows="4" placeholder="อยากเห็นอะไรในเกมนี้…">{{ old('comment') }}</textarea></label>
<label class="gs-check"><input type="checkbox" name="publish_comment" value="1" @checked(old('publish_comment'))> แสดงคำแนะนำนี้หลังทีมตรวจข้อความ หากไม่เปิดเผยชื่อจะแสดงแบบไม่ระบุตัวตน</label>
<label class="gs-check"><input type="checkbox" name="consent" value="1" required> ยินยอมให้บริษัทเก็บสลิปและข้อมูลรายการเพื่อยืนยันการโอนและจัดการรางวัล เข้าใจว่าการสนับสนุนไม่ใช่การสั่งซื้อเกมเต็ม</label><button class="gs-button" type="submit">ส่งสลิปและคำแนะนำ</button><small>การกดส่งไม่ใช่การโอนเงิน รอตรวจเงินเข้าก่อนยอดและรางวัลจะได้รับการยืนยัน</small></form>
@else<p>เข้าสู่ระบบ XMAN ID เพื่อแนบสลิป ติดตามผล และรับรางวัลในบัญชีเดียวกัน</p><a class="gs-button" href="{{ route('game-support.join', $campaign) }}">เข้าสู่ระบบเพื่อแจ้งโอน</a>@endauth
</section><section class="gs-card"><h2>รางวัลผู้สนับสนุน</h2><p class="gs-muted">เลือกระดับสูงสุดที่ยอดรายการนั้นถึง ไม่มีโบนัสพลังในเกม รางวัลถูกบันทึกตามเงื่อนไขตอนส่งรายการ</p>@foreach($campaign->tiers as $tier)<div class="gs-reward"><strong>{{ $tier['name'] }} · ฿{{ number_format($tier['minimum']) }}</strong><ul>@foreach($tier['rewards'] as $r)<li>{{ $r }}</li>@endforeach</ul></div>@endforeach
<h2>โหวตและให้ดาว</h2><p>{{ $stats['votes'] }} โหวต · {{ $stats['rating_count'] ? number_format($stats['stars'], 2).' ★ จาก '.$stats['rating_count'].' คะแนน' : 'ยังไม่มีคะแนนดาว' }}</p>
@auth<form method="post" action="{{ route('game-support.vote', $campaign) }}">@csrf<button class="gs-button" type="submit">{{ $myVote === $campaign->id ? '✓ คุณเลือกเกมนี้ไว้แล้ว' : 'อยากให้ทำเกมนี้มากที่สุด' }}</button></form><p class="gs-muted">มีหนึ่งโหวตหลักต่อบัญชี การเลือกเกมนี้จะย้ายโหวตจากเกมเดิม</p><form method="post" action="{{ route('game-support.rate', $campaign) }}" class="gs-form">@csrf<label>คะแนนของคุณ<select name="stars" required><option value="">เลือกคะแนน</option>@foreach([5,4,3,2,1] as $star)<option value="{{ $star }}" @selected($myRating === $star)>{{ $star }} ดาว</option>@endforeach</select></label><button type="submit" class="gs-small">บันทึกคะแนน</button></form>@else<a href="{{ route('game-support.join', $campaign) }}">เข้าสู่ระบบเพื่อโหวตและให้ดาว</a>@endauth
</section></div>
@if($mine->isNotEmpty())<section class="gs-card"><h2>รายการของฉัน</h2>@foreach($mine as $d)<div class="gs-reward"><b>฿{{ number_format($d->amount_satang / 100, 2) }} · {{ ['pending'=>'รอตรวจสลิป','approved'=>'ยืนยันแล้ว','rejected'=>'ไม่ผ่านการตรวจ','void'=>'ยกเลิกการนับยอด'][$d->status] }}</b><p>เลขรายการ {{ $d->public_id }}</p><p>{{ $d->reward_snapshot['name'] }} · {{ ['pending'=>'รอยืนยัน','available'=>'ได้รับสิทธิ์แล้ว','delivered'=>'ส่งมอบแล้ว','not_eligible'=>'ยังไม่ได้รับสิทธิ์','revoked'=>'ยกเลิกสิทธิ์'][$d->reward_status] }}</p><ul>@foreach($d->reward_snapshot['rewards'] as $reward)<li>{{ $reward }}</li>@endforeach</ul>@if($d->review_note)<p>ผลตรวจ: {{ $d->review_note }}</p>@endif</div>@endforeach</section>@endif
<section class="gs-card"><h2>รายนามผู้สนับสนุนที่ยืนยันแล้ว</h2><p class="gs-muted">แสดงเฉพาะผู้ที่ยินยอมเปิดเผยชื่อ ยอดรวมด้านบนรวมผู้ไม่เปิดเผยชื่อด้วย</p>@forelse($donors as $d)<div class="gs-donor"><strong>{{ $d->display_name }}</strong><span>฿{{ number_format($d->amount_satang / 100, 2) }}</span><span class="gs-tag">{{ $d->reward_snapshot['name'] }}</span><small>{{ $d->reward_status === 'delivered' ? 'ส่งมอบรางวัลแล้ว' : 'ได้รับสิทธิ์แล้ว' }}</small></div>@empty<p>ยังไม่มีรายนามที่อนุญาตให้แสดง</p>@endforelse{{ $donors->links() }}</section>
<section class="gs-card" id="comments"><h2>คำแนะนำจากผู้เล่น</h2>@auth<form action="{{ route('game-support.comment', $campaign) }}" method="post" class="gs-form">@csrf<label>ชื่อที่แสดง<input name="display_name" maxlength="80" value="{{ old('display_name', auth()->user()->name) }}" required></label><label>อยากให้เกมนี้มีอะไรเพิ่ม<textarea name="body" maxlength="2000" rows="3" required>{{ old('body') }}</textarea></label><button class="gs-button" type="submit">ส่งคำแนะนำ</button><small>ข้อความจะแสดงต่อสาธารณะเมื่อทีมตรวจแล้ว ไม่ต้องบริจาคก็แนะนำได้</small></form>@else<a href="{{ route('game-support.join', $campaign) }}">เข้าสู่ระบบเพื่อฝากคำแนะนำ</a>@endauth
@forelse($comments as $c)<article class="gs-reward"><strong>{{ $c->display_name }}</strong><p class="gs-comment">{{ $c->body }}</p></article>@empty<p class="gs-muted">ยังไม่มีความคิดเห็นที่เผยแพร่</p>@endforelse{{ $comments->links() }}</section>
@endsection
