@extends('game-support.layout')
@section('title', $campaign->name)
@section('crumb', $campaign->name)
@section('content')
<a href="{{ route('game-support.index') }}">← อันดับและเกมทั้งหมด</a><div class="gs-hero"><span class="gs-tag">SUPPORT THE NEXT MISSION</span><h1>{{ $campaign->name }}</h1><p>{{ $campaign->description }}</p><div class="gs-metrics"><strong>฿{{ number_format($stats['raised'], 2) }}</strong><span>@if($stats['goal'])จากเป้า ฿{{ number_format($stats['goal']) }}@elseยังไม่กำหนดเป้าทุน@endif · {{ $stats['supporters'] }} ผู้สนับสนุน</span></div>@if($stats['goal'])<progress max="{{ $stats['goal'] }}" value="{{ min($stats['raised'], $stats['goal']) }}" aria-label="ยอดสนับสนุนที่ตรวจแล้ว"></progress>@endif</div>
<div class="gs-grid"><section class="gs-card" id="donate"><h2>ร่วมสนับสนุนเกมนี้</h2><div class="gs-bank"><img src="{{ asset('images/banks/scb.svg') }}" alt="ธนาคารไทยพาณิชย์" width="150" height="45"><div><b>{{ $bank['name'] }}</b><p>{{ $bank['holder'] }}</p><strong class="gs-account">{{ $bank['account'] }}</strong><button type="button" data-copy="4111484769" class="gs-small">คัดลอกเลขบัญชี</button><span data-copy-status role="status"></span></div></div><p class="gs-muted">ใช้บัญชีบริษัทเดียวกันทุกเกม เลือกยอด โอนผ่านแอปธนาคาร แล้วแนบสลิปที่นี่ ตรวจชื่อผู้รับก่อนโอน เลขนี้เป็นบัญชีธนาคาร ไม่ใช่หมายเลขพร้อมเพย์</p>
@auth
<form method="post" enctype="multipart/form-data" action="{{ route('game-support.donate', $campaign) }}" class="gs-form">@csrf
<label>ยอดที่โอน (บาท)<input id="donation-amount" name="amount" inputmode="decimal" pattern="[0-9]+(\.[0-9]{1,2})?" value="{{ old('amount', is_scalar(request('amount')) ? request('amount', '300') : '300') }}" required></label>
<div class="gs-presets">@foreach($campaign->tiers as $tier)<button type="button" data-amount="{{ $tier['minimum'] }}">฿{{ number_format($tier['minimum']) }}</button>@endforeach</div>
<label>ชื่อสำหรับรายการ / ชื่อที่อยากแสดง<input name="display_name" maxlength="80" value="{{ old('display_name', auth()->user()->name) }}" required></label>
<label class="gs-check"><input type="checkbox" name="publish_name" value="1" @checked(old('publish_name'))> ยินยอมแสดงชื่อนี้ ยอด และรางวัลบนหน้าผู้สนับสนุน</label>
<label>สลิปการโอน (JPG / PNG / WebP ไม่เกิน 5 MB)<input type="file" name="slip" accept="image/jpeg,image/png,image/webp" required></label>
<label>คำแนะนำถึงทีม (ไม่บังคับ)<textarea name="comment" maxlength="2000" rows="4" placeholder="อยากเห็นอะไรในเกมนี้…">{{ old('comment') }}</textarea></label>
<label class="gs-check"><input type="checkbox" name="publish_comment" value="1" @checked(old('publish_comment'))> แสดงคำแนะนำนี้หลังทีมตรวจข้อความ หากไม่เปิดเผยชื่อจะแสดงแบบไม่ระบุตัวตน</label>
<label class="gs-check"><input type="checkbox" name="consent" value="1" required> ยินยอมให้บริษัทเก็บสลิปและข้อมูลรายการเพื่อยืนยันการโอนและจัดการรางวัล เข้าใจว่าการสนับสนุนไม่ใช่การสั่งซื้อเกมเต็ม</label><button class="gs-button" type="submit">ส่งสลิปและคำแนะนำ</button><small>การกดส่งไม่ใช่การโอนเงิน รอตรวจเงินเข้าก่อนยอดและรางวัลจะได้รับการยืนยัน</small></form>
@else<p>เข้าสู่ระบบ XMAN ID เพื่อแนบสลิป ติดตามผล และรับรางวัลในบัญชีเดียวกัน</p><a class="gs-button" href="{{ route('game-support.join', $campaign) }}">เข้าสู่ระบบเพื่อแจ้งโอน</a>@endauth
</section><section class="gs-card"><h2>รางวัลผู้สนับสนุน</h2><p class="gs-muted">เลือกระดับสูงสุดที่ยอดรายการนั้นถึง ไม่มีโบนัสพลังในเกม รางวัลถูกบันทึกตามเงื่อนไขตอนส่งรายการ</p>@php($itemNames = $campaign->items->pluck('name', 'key'))@foreach($campaign->tiers as $tier)<div class="gs-reward"><strong>{{ $tier['name'] }} · ฿{{ number_format($tier['minimum']) }}</strong><ul>@foreach($tier['rewards'] as $r)<li>{{ $r }}</li>@endforeach @foreach($tier['items'] ?? [] as $key)@if($itemNames->has($key))<li>ไอเท็มในเกม: {{ $itemNames[$key] }}</li>@endif @endforeach</ul></div>@endforeach
<h2>โหวตและให้ดาว</h2><p>{{ $stats['votes'] }} โหวต · {{ $stats['rating_count'] ? number_format($stats['stars'], 2).' ★ จาก '.$stats['rating_count'].' คะแนน' : 'ยังไม่มีคะแนนดาว' }}</p>
@auth<form method="post" action="{{ route('game-support.vote', $campaign) }}">@csrf<button class="gs-button" type="submit">{{ $myVote === $campaign->id ? '✓ คุณเลือกเกมนี้ไว้แล้ว' : 'อยากให้ทำเกมนี้มากที่สุด' }}</button></form><p class="gs-muted">มีหนึ่งโหวตหลักต่อบัญชี การเลือกเกมนี้จะย้ายโหวตจากเกมเดิม</p><form method="post" action="{{ route('game-support.rate', $campaign) }}" class="gs-form">@csrf<label>คะแนนของคุณ<select name="stars" required><option value="">เลือกคะแนน</option>@foreach([5,4,3,2,1] as $star)<option value="{{ $star }}" @selected($myRating === $star)>{{ $star }} ดาว</option>@endforeach</select></label><button type="submit" class="gs-small">บันทึกคะแนน</button></form>@else<a href="{{ route('game-support.join', $campaign) }}">เข้าสู่ระบบเพื่อโหวตและให้ดาว</a>@endauth
</section></div>
@if($mine->isNotEmpty())<section class="gs-card"><h2>รายการของฉัน</h2>@foreach($mine as $d)<div class="gs-reward"><b>฿{{ number_format($d->amount_satang / 100, 2) }} · {{ ['pending'=>'รอตรวจสลิป','approved'=>'ยืนยันแล้ว','rejected'=>'ไม่ผ่านการตรวจ','void'=>'ยกเลิกการนับยอด'][$d->status] }}</b><p>เลขรายการ {{ $d->public_id }}</p><p>{{ $d->reward_snapshot['name'] }} · {{ ['pending'=>'รอยืนยัน','available'=>'ได้รับสิทธิ์แล้ว','delivered'=>'ส่งมอบแล้ว','not_eligible'=>'ยังไม่ได้รับสิทธิ์','revoked'=>'ยกเลิกสิทธิ์'][$d->reward_status] }}</p><ul>@foreach($d->reward_snapshot['rewards'] as $reward)<li>{{ $reward }}</li>@endforeach</ul>@if($d->entitlements->isNotEmpty())<p>ไอเท็มในเกม:</p><ul>@foreach($d->entitlements as $e)<li>{{ $e->item->name }} · @if($e->status === 'granted')<code class="gs-code">{{ $e->code }}</code> <a href="{{ rtrim(config('game-support.hub_origin'), '/') }}/#redeem={{ $e->code }}" target="_blank" rel="noopener">แลกบนเว็บเกม ↗</a> ใช้แล้ว {{ $e->redeem_count }}/{{ $e->item->max_devices }} เครื่อง @else ยกเลิกแล้ว @endif</li>@endforeach</ul>@elseif(! empty($d->reward_snapshot['items']))<p>ไอเท็มในเกม: {{ collect($d->reward_snapshot['items'])->pluck('name')->implode(', ') }} (ได้โค้ดเมื่อทีมยืนยันยอด)</p>@endif @if($d->review_note)<p>ผลตรวจ: {{ $d->review_note }}</p>@endif</div>@endforeach<p><a href="{{ route('game-support.my-items') }}">ดูไอเท็มและโค้ดทั้งหมดของฉัน →</a></p></section>@endif
<section class="gs-card"><h2>รายนามผู้สนับสนุนที่ยืนยันแล้ว</h2><p class="gs-muted">แสดงเฉพาะผู้ที่ยินยอมเปิดเผยชื่อ ยอดรวมด้านบนรวมผู้ไม่เปิดเผยชื่อด้วย</p>@forelse($donors as $d)<div class="gs-donor"><strong>{{ $d->display_name }}</strong><span>฿{{ number_format($d->amount_satang / 100, 2) }}</span><span class="gs-tag">{{ $d->reward_snapshot['name'] }}</span><small>{{ $d->reward_status === 'delivered' ? 'ส่งมอบรางวัลแล้ว' : 'ได้รับสิทธิ์แล้ว' }}</small></div>@empty<p>ยังไม่มีรายนามที่อนุญาตให้แสดง</p>@endforelse{{ $donors->links() }}</section>
<section class="gs-card" id="reviews"><h2>รีวิวจากผู้เล่น</h2><p class="gs-muted">{{ $stats['rating_count'] ? number_format($stats['stars'], 2).' ★ จาก '.$stats['rating_count'].' คะแนน' : 'ยังไม่มีคะแนนดาว' }} · รีวิวที่อนุมัติแล้ว {{ $reviews->total() }} รายการ แสดงในหน้าเกมและในฮับ</p>
@auth
@if($myReview)<p class="gs-muted">รีวิวของคุณ: {{ ['pending' => 'รอทีมตรวจ', 'approved' => 'เผยแพร่แล้ว', 'rejected' => 'ไม่ผ่านการตรวจ'][$myReview->status] ?? $myReview->status }}@if($myReview->status === 'rejected' && $myReview->admin_note) — {{ $myReview->admin_note }}@endif · แก้ไขแล้วส่งใหม่จะกลับไปรอตรวจ</p>@endif
<form method="post" action="{{ route('game-support.review', $campaign) }}" class="gs-form">@csrf
<label>ให้ดาว<select name="rating" required><option value="">เลือกคะแนน</option>@foreach([5,4,3,2,1] as $star)<option value="{{ $star }}" @selected((int) old('rating', $myReview?->rating) === $star)>{{ str_repeat('★', $star) }} {{ $star }} ดาว</option>@endforeach</select></label>
<label>หัวข้อ (ไม่บังคับ)<input name="title" maxlength="100" value="{{ old('title', $myReview?->title) }}"></label>
<label>เล่นแล้วเป็นอย่างไร<textarea name="comment" minlength="10" maxlength="2000" rows="4" required placeholder="ชอบอะไร อยากให้ปรับอะไร…">{{ old('comment', $myReview?->comment) }}</textarea></label>
<button class="gs-button" type="submit">{{ $myReview ? 'บันทึกรีวิว' : 'ส่งรีวิว' }}</button><small>ดาวนับในคะแนนเฉลี่ยทันที ข้อความแสดงหลังทีมตรวจ ชื่อจะแสดงแบบย่อ</small></form>
@else<a href="{{ route('game-support.join', $campaign) }}">เข้าสู่ระบบเพื่อเขียนรีวิว</a>@endauth
@forelse($reviews as $r)<article class="gs-reward"><strong>{{ str_repeat('★', $r->rating) }} {{ \App\Http\Controllers\GamesHubController::publicName($r->user?->name) }}</strong>@if($r->is_featured) <span class="gs-tag">รีวิวแนะนำ</span>@endif @if($r->title)<p><b>{{ $r->title }}</b></p>@endif<p class="gs-comment">{{ $r->comment }}</p><small>{{ ($r->approved_at ?? $r->created_at)->format('Y-m-d') }}</small></article>@empty<p class="gs-muted">ยังไม่มีรีวิวที่เผยแพร่</p>@endforelse{{ $reviews->links() }}</section>
<section class="gs-card" id="comments"><h2>คำแนะนำจากผู้เล่น</h2>@auth<form action="{{ route('game-support.comment', $campaign) }}" method="post" class="gs-form">@csrf<label>ชื่อที่แสดง<input name="display_name" maxlength="80" value="{{ old('display_name', auth()->user()->name) }}" required></label><label>อยากให้เกมนี้มีอะไรเพิ่ม<textarea name="body" maxlength="2000" rows="3" required>{{ old('body') }}</textarea></label><button class="gs-button" type="submit">ส่งคำแนะนำ</button><small>ข้อความจะแสดงต่อสาธารณะเมื่อทีมตรวจแล้ว ไม่ต้องบริจาคก็แนะนำได้</small></form>@else<a href="{{ route('game-support.join', $campaign) }}">เข้าสู่ระบบเพื่อฝากคำแนะนำ</a>@endauth
@forelse($comments as $c)<article class="gs-reward"><strong>{{ $c->display_name }}</strong><p class="gs-comment">{{ $c->body }}</p></article>@empty<p class="gs-muted">ยังไม่มีความคิดเห็นที่เผยแพร่</p>@endforelse{{ $comments->links() }}</section>
@endsection
